# Bar Path Model

### Training a model for bar path tracking

In [1]:
import numpy as np
import pandas as pd

## Grab data from AirTable

In [2]:
from ast import literal_eval
from pyairtable import Api as airtable_api

In [3]:
def to_numpy(data):
    return np.array(literal_eval(data))

In [4]:
AIR_TABLE_API_KEY = 'patMswkrKzfHWSG3U.a882cccc6e7709b3a24b42b7f9c0ccd48ed15614f13c54e4d3dbaa55ba8ffffb'
BASE_ID = 'appaCiWbsAFmlkOLF'
TABLE_NAME = 'tblZtbDVHfCaoTnsH'
BASE_URL = 'https://api.airtable.com/v0/'

EXERCISE = '*'
VALID_DATA = 'true'
MIN_REPS = '1'

FORMULA = "AND({ValidData} = 'true', " + \
        "{Reps} >= '" + MIN_REPS + "')"
FORMULA

"AND({ValidData} = 'true', {Reps} >= '1')"

In [5]:
api = airtable_api(AIR_TABLE_API_KEY)
table = api.table(BASE_ID, TABLE_NAME)

matches = table.all(formula=FORMULA)
print("Number of matching records: ", len(matches))

Number of matching records:  508

In [6]:
df = pd.DataFrame(columns=[
    'Date',
    'Exercise',
    'Lifter',
    'WorkoutTime',
    'Reps',
    'Weight',
    'Intensity',
    'Notes',
    'StartRepTime',
    'EndRepTime',
    'Counter',
    'TimeBetweenSamples',
    'AccX',
    'AccY',
    'AccZ',
    'Pitch',
    'Roll',
    'Yaw',
    'HeartRate'
])

data_dict = []

for match in matches:
    data = match['fields']
    
    data_dict.append({
        'Date': data.get('Date'),
        'Exercise': data.get('Exercise'),
        'Lifter': data.get('Lifter'),
        'WorkoutTime': data.get('WorkoutTime'),
        'Reps': data.get('Reps'),
        'Weight': data.get('Weight'),
        'Intensity': data.get('Intensity'),
        'Notes': data.get('Notes'),
        'StartRepTime': data.get('StartDateTime'),
        'EndRepTime': data.get('EndDateTime'),
        'Counter': to_numpy(data.get('Counter')),
        'TimeBetweenSamples': to_numpy(data.get('TimeBetweenSamples')),
        'AccX': to_numpy(data.get('AccX')),
        'AccY': to_numpy(data.get('AccY')),
        'AccZ': to_numpy(data.get('AccZ')),
        'Pitch': to_numpy(data.get('Pitch')),
        'Roll': to_numpy(data.get('Roll')),
        'Yaw': to_numpy(data.get('Yaw')),
        'HeartRate': to_numpy(data.get('HeartRate')),
    })

df = pd.concat([pd.DataFrame([d]) for d in data_dict], ignore_index=True)

In [7]:
df

,Date,Exercise,Lifter,WorkoutTime,Reps,Weight,Intensity,Notes,StartRepTime,EndRepTime,Counter,TimeBetweenSamples,AccX,AccY,AccZ,Pitch,Roll,Yaw,HeartRate
0,"Jul 17, 2024 at 8:37:11 PM",DB Side Raise,Anwar,32.25,9,27.5,9,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[663011, 9, 9, 10, 10, 10, 13, 7, 10, 10, 10, ...","[-0.327, 0.068, 0.159, -0.036, -0.125, -0.051,...","[-0.15, -0.236, -0.011, 0.169, 0.05, -0.098, -...","[0.03, 0.009, -0.077, -0.052, 0.05, 0.151, 0.1...","[0.346, 0.346, 0.347, 0.347, 0.348, 0.348, 0.3...","[0.093, 0.093, 0.092, 0.092, 0.092, 0.092, 0.0...","[-0.016, -0.016, -0.015, -0.015, -0.015, -0.01...","[110, 110, 110, 110, 110, 110, 110, 110, 110, ..."
1,"May 20, 2024 at 1:44:48 PM",Bench,Anwar,47.67,7,195,10,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[258264, 7, 9, 9, 10, 10, 10, 10, 11, 9, 10, 1...","[0.13, -0.052, -0.069, -0.006, -0.048, 0.075, ...","[-0.17, -0.157, -0.054, -0.044, -0.078, -0.024...","[0.147, 0.036, -0.106, -0.231, -0.274, -0.156,...","[0.15, 0.15, 0.151, 0.151, 0.152, 0.152, 0.152...","[0.059, 0.059, 0.058, 0.058, 0.058, 0.058, 0.0...","[-0.004, -0.004, -0.003, -0.002, -0.002, -0.00...","[93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 9..."
2,"Apr 16, 2024 at 4:45:01 PM",Horizontal Chest Press,Anwar,28.69,8,145,10,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[222003, 10, 9, 10, 10, 10, 12, 7, 10, 10, 10,...","[0.254, 0.409, -0.13, -0.019, 0.234, 0.331, 0....","[0.819, -0.072, -0.617, -1.169, -0.67, 0.128, ...","[0.095, 0.315, 0.715, 0.66, 0.735, 0.698, 0.82...","[0.667, 0.674, 0.676, 0.683, 0.694, 0.704, 0.7...","[0.057, 0.059, 0.063, 0.068, 0.074, 0.078, 0.0...","[-0.02, -0.022, -0.027, -0.034, -0.038, -0.04,...","[84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 8..."
3,"Apr 27, 2024 at 11:07:05 AM",Squat,Anwar,46.75,7,225,9,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[242417, 13, 7, 9, 11, 9, 10, 10, 10, 12, 8, 1...","[0.119, -0.129, -0.155, -0.134, -0.003, 0.076,...","[0.138, -0.047, -0.156, -0.166, -0.181, -0.138...","[0.152, 0.149, 0.097, 0.144, 0.222, 0.199, 0.0...","[0.526, 0.528, 0.529, 0.529, 0.528, 0.527, 0.5...","[0.023, 0.022, 0.022, 0.022, 0.022, 0.022, 0.0...","[-0.006, -0.005, -0.005, -0.005, -0.004, -0.00...","[124, 124, 124, 124, 124, 124, 124, 124, 124, ..."
4,"Mar 2, 2024 at 3:35:29 PM",DB Side Raise,Anwar,32.91,12,27.5,8,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[95273, 10, 11, 11, 8, 11, 10, 9, 11, 9, 10, 1...","[-0.151, 0.003, -0.038, 0.02, 0.008, -0.123, -...","[0.203, 0.355, 0.324, 0.137, 0.029, -0.009, 0....","[-0.006, -0.054, -0.154, -0.193, -0.148, -0.10...","[0.401, 0.402, 0.403, 0.404, 0.405, 0.405, 0.4...","[0.123, 0.124, 0.124, 0.124, 0.124, 0.123, 0.1...","[-0.025, -0.025, -0.024, -0.023, -0.023, -0.02...","[123, 123, 123, 123, 123, 123, 123, 123, 123, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,"Jul 1, 2024 at 9:47:35 AM",Squat,Anwar,52.21,10,135,7,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[72575461, 3, 10, 10, 10, 12, 8, 10, 10, 10, 1...","[0.036, -0.065, -0.125, -0.223, -0.196, -0.067...","[0.073, -0.05, -0.119, -0.137, -0.064, 0.013, ...","[-0.074, -0.03, 0.004, 0.07, 0.083, 0.084, 0.1...","[0.278, 0.278, 0.279, 0.278, 0.278, 0.277, 0.2...","[-0.014, -0.014, -0.014, -0.014, -0.014, -0.01...","[0.002, 0.002, 0.003, 0.004, 0.004, 0.004, 0.0...","[108, 108, 108, 108, 108, 108, 108, 108, 108, ..."
504,"Jul 10, 2024 at 7:33:10 AM",Squat,Anwar,46.25,8,155,8,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[197961, 9, 7, 10, 10, 10, 15, 5, 10, 10, 10, ...","[0.53, 0.045, -0.128, 0.029, 0.104, 0.091, 0.0...","[0.232, 0.072, -0.104, -0.453, -0.642, -0.353,...","[-0.328, -0.029, 0.144, -0.023, -0.127, -0.143...","[0.262, 0.263, 0.261, 0.258, 0.256, 0.255, 0.2...","[0.11, 0.112, 0.112, 0.112, 0.112, 0.112, 0.11...","[-0.015, -0.013, -0.012, -0.011, -0.01, -0.009...","[102, 102, 102, 102, 102, 102, 102, 102, 102, ..."
505,"May 31, 2024 at 5:41:02 PM",Row,Anwar,32.66,10,125,9,Pulled from floor,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[143424, 11, 7, 9, 10, 10, 12, 7, 10, 10, 10, ...","[0.093, 0.146, 0.015, -0.046, -0.021, 0.031, -...","[-0.053, 0.073, 0.129, 0.146, 0.135, 0.109, -0...","[-0.002, -0.099, -0.101, -0.039, 0.048, 0.102,...","[0.13, 0.132, 0.133, 0.134, 0.135, 0.136, 0.13...","[-0.034, -0.034, -0.034, -0.034, -0.034, -0.03...","[0.002, 0.003, 0.004, 0.004, 0.004, 0.005, 0.0...","[114, 114, 114, 114, 114, 114, 114, 114, 114, ..."
506,"Jun 20, 2024 at 5:21:43 PM",Bench,Anwar,35.63,3,225,9,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[162596, 6, 9, 10, 10, 11, 10, 10, 10, 10, 10,...","[-0.179, -0.718, 0.043, 0.698, 0.59, 0.084, -0...","[0.146, -0.827, -0.338, 0.319, 0.126, 0.046, 0...","[-0.001, 0.015, -0.047, 0.071, 0.082, -0.043, ...","[0.735, 0.732, 0.73, 0.728, 0.727, 0.726, 0.72...","[0.034, 0.032, 0.031, 0.03, 0.03, 0.031, 0.031...","[-0.013, -0.008, -0.006, -0.007, -0.007, -0.00...","[103, 103, 103, 103, 103, 103, 103, 103, 103, ..."
507,"Mar 17, 2024 at 1:50:40 PM",Bench,Anwar,37.18,7,205,9,None,None,None,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[207844, 12, 7, 10, 14, 6, 10, 10, 10, 14, 6, ...","[0.519, 0.386, 0.243, 0.218, -0.0, -0.175, -0....","[-0.094, -0.163, 0.192, 0.026, -0.456, -0.446,...","[-0.164, -0.297, -0.304, -0.29, -0.202, -0.217...","[0.675, 0.673, 0.67, 0.666, 0.662, 0.657, 0.65...","[-0.018, -0.019, -0.022, -0.024, -0.025, -0.02...","[0.006, 0.008, 0.008, 0.009, 0.01, 0.01, 0.011...","[114, 114, 114, 114, 114, 114, 114, 114, 114, ..."

## Filter and integrate

In [8]:
from scipy.integrate import cumulative_trapezoid
from scipy.signal import find_peaks, filtfilt, butter

In [9]:
CUTOFF_FREQ = 0.1
SAMPLE_RATE = 100

In [10]:
def filter(data, cutoff_freq, sample_rate):
    b, a = butter(1, 2 * cutoff_freq / (sample_rate), btype="highpass")
    return filtfilt(b, a, data)

In [11]:
df['AccX'] = df['AccX'].apply(lambda x: filter(x, CUTOFF_FREQ, SAMPLE_RATE))
df['AccY'] = df['AccY'].apply(lambda x: filter(x, CUTOFF_FREQ, SAMPLE_RATE))
df['AccZ'] = df['AccZ'].apply(lambda x: filter(x, CUTOFF_FREQ, SAMPLE_RATE))

df['VelX'] = df['AccX'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['VelY'] = df['AccY'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['VelZ'] = df['AccZ'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))

df['PosX'] = df['VelX'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['PosY'] = df['VelY'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['PosZ'] = df['VelZ'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))

In [12]:
df

,Date,Exercise,Lifter,WorkoutTime,Reps,Weight,Intensity,Notes,StartRepTime,EndRepTime,...,Pitch,Roll,Yaw,HeartRate,VelX,VelY,VelZ,PosX,PosY,PosZ
0,"Jul 17, 2024 at 8:37:11 PM",DB Side Raise,Anwar,32.25,9,27.5,9,None,None,None,...,"[0.346, 0.346, 0.347, 0.347, 0.348, 0.348, 0.3...","[0.093, 0.093, 0.092, 0.092, 0.092, 0.092, 0.0...","[-0.016, -0.016, -0.015, -0.015, -0.015, -0.01...","[110, 110, 110, 110, 110, 110, 110, 110, 110, ...","[-0.0014649357731003226, -0.000542179054009387...","[-0.0032268163950093065, -0.005780262947442648...","[-0.002822331502439393, -0.00620518283964074, ...","[-1.0035574135548553e-05, -1.365508205041934e-...","[-4.5035396712259775e-05, -0.00010558884814046...","[-4.513757171040066e-05, -0.000125756912375465..."
1,"May 20, 2024 at 1:44:48 PM",Bench,Anwar,47.67,7,195,10,None,None,None,...,"[0.15, 0.15, 0.151, 0.151, 0.152, 0.152, 0.152...","[0.059, 0.059, 0.058, 0.058, 0.058, 0.058, 0.0...","[-0.004, -0.004, -0.003, -0.002, -0.002, -0.00...","[93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 9...","[-0.001885159146155135, -0.004768013126674952,...","[-0.0012504236471545327, -0.001937488616831735...","[-0.0021596804416947946, -0.005581177378450727...","[-3.326586136415044e-05, -9.422424531492847e-0...","[-1.5939561319931343e-05, -3.600811531290046e-...","[-3.8704289100727604e-05, -0.00011828330888627..."
2,"Apr 16, 2024 at 4:45:01 PM",Horizontal Chest Press,Anwar,28.69,8,145,10,None,None,None,...,"[0.667, 0.674, 0.676, 0.683, 0.694, 0.704, 0.7...","[0.057, 0.059, 0.063, 0.068, 0.074, 0.078, 0.0...","[-0.02, -0.022, -0.027, -0.034, -0.038, -0.04,...","[84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 8...","[0.0004675774809815621, -0.0009999711671855487...","[-0.008408468908998774, -0.023950916406364545,...","[0.006135834363124537, 0.015358291481753328, 0...","[-2.661968431019933e-06, -3.077535453345486e-0...","[-0.00016179692657681662, -0.00050621620542948...","[0.00010747062922438932, 0.0003157256960279543..."
3,"Apr 27, 2024 at 11:07:05 AM",Squat,Anwar,46.75,7,225,9,None,None,None,...,"[0.526, 0.528, 0.529, 0.529, 0.528, 0.527, 0.5...","[0.023, 0.022, 0.022, 0.022, 0.022, 0.022, 0.0...","[-0.006, -0.005, -0.005, -0.005, -0.004, -0.00...","[124, 124, 124, 124, 124, 124, 124, 124, 124, ...","[-0.0030456982753375816, -0.007465214832760417...","[-0.0021342010224980512, -0.005732654568981559...","[0.00026756050383020804, 0.0002661151344521119...","[-5.255456554049e-05, -0.0001494491940834048, ...","[-3.933427795739806e-05, -0.000117600021137272...","[2.6683781914116e-06, 5.227285374899985e-06, 1..."
4,"Mar 2, 2024 at 3:35:29 PM",DB Side Raise,Anwar,32.91,12,27.5,8,None,None,None,...,"[0.401, 0.402, 0.403, 0.404, 0.405, 0.405, 0.4...","[0.123, 0.124, 0.124, 0.124, 0.124, 0.123, 0.1...","[-0.025, -0.025, -0.024, -0.023, -0.023, -0.02...","[123, 123, 123, 123, 123, 123, 123, 123, 123, ...","[-0.00184206650063898, -0.0031435479399833204,...","[-0.0005986733359109622, -0.000591368475920483...","[-0.0034140190432674577, -0.007582616969428559...","[-2.49280722031115e-05, -6.256831408699818e-05...","[-5.950209059157229e-06, -1.7272560743230407e-...","[-5.498318006348008e-05, -0.000155201054444126..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,"Jul 1, 2024 at 9:47:35 AM",Squat,Anwar,52.21,10,135,7,None,None,None,...,"[0.278, 0.278, 0.279, 0.278, 0.278, 0.277, 0.2...","[-0.014, -0.014, -0.014, -0.014, -0.014, -0.01...","[0.002, 0.002, 0.003, 0.004, 0.004, 0.004, 0.0...","[108, 108, 108, 108, 108, 108, 108, 108, 108, ...","[-0.002169738259607821, -0.005149523572902614,...","[-0.001003855858773578, -0.002965863027656032,...","[0.0007584486703332916, 0.0018993700315078452,...","[-3.6596309162552174e-05, -0.00010696629418197...","[-1.984859443214805e-05, -6.148337848658976e-0...","[1.3289093509205683e-05, 4.044999472528927e-05..."
504,"Jul 10, 2024 at 7:33:10 AM",Squat,Anwar,46.25,8,155,8,None,None,None,...,"[0.262, 0.263, 0.261, 0.258, 0.256, 0.255, 0.2...","[0.11, 0.112, 0.112, 0.112, 0.112, 0.112, 0.11...","[-0.015, -0.013, -0.012, -0.011, -0.01, -0.009...","[102, 102, 102, 102, 102, 102, 102, 102, 102, ...","[-0.003529311215096452, -0.010324849890771395,...","[-0.0014397094106799574, -0.004546569006634747...","[0.0005644624857346961, 0.0034697483119282497,...","[-6.927080552933923e-05, -0.000206779318116197...","[-2.9931392086573524e-05, -0.00010399279097330...","[2.017105398831473e-05, 6.944954144794567e-05,..."
505,"May 31, 2024 at 5:41:02 PM",Row,Anwar,32.66,10,125,9,Pulled from floor,None,None,...,"[0.13, 0.132, 0.133, 0.134, 0.135, 0.136, 0.13...","[-0.034, -0.034, -0.034, -0.034, -0.034, -0.03...","[0.002, 0.003, 0.004, 0.004, 0.004, 0.005, 0.0...","[114, 114, 114, 114, 114, 114, 114, 114, 114, ...","[-0.0031419583802117404, -0.006688355598364374...","[-0.0011560402429562965, -0.001413695408873975...","[-0.002084372957850829, -0.0046820481028725675...","[-4.915156989288057e-05, -0.000138640034328094...","[-1.284867825915136e-05, -2.650706054732862e-0...","[-3.3832105303616986e-05, -9.223294652993864e-..."
506,"Jun 20, 2024 at 5:21:43 PM",Bench,Anwar,35.63,3,225,9,None,None,None,...,"[0.735, 0.732, 0.73, 0.728, 0.727, 0.726, 0.72...","[0.034, 0.032, 0.031, 0.03, 0.03, 0.031, 0.031...","[-0.013, -0.008, -0.006, -0.007, -0.007, -0.00...","[103, 103, 103, 103, 103, 103, 103, 103, 103, ...","[-0.007528969687001486, -0.013974998233588814,...","[-0.006722948802778982, -0.015886110541789948,...","[-0.0030544699621362437, -0.006355339169308515...","[-0.0001075198396029515, -0.000244236236773132...","[-0.00011304529672284464, -0.00028917468208934...","[-4.70490456572238e-05, -0.0001257894060196283..."
507,"Mar 17, 2024 at 1:50:40 PM",Bench,Anwar,37.18,7,205,9,None,None,None,...,"[0.675, 0.673, 0.67, 0.666, 0.662, 0.657, 0.65...","[-0.018, -0.019, -0.022, -0.024, -0.025, -0.02...","[0.006, 0.008, 0.008, 0.009, 0.01, 0.01, 0.011...","[114, 114, 114, 114, 114, 114, 114, 114, 114, ...","[-0.004350002708439205, -0.010061628623400933,...","[-0.005228946119625838, -0.009032876950541974,...","[-0.0019626293490625285, -0.00463315988441673,...","[-7.205815665920069e-05, -0.000205341789300572...","[-7.130911535083906e-05, -0.000175958237379676...","[-3.297894616739629e-05, -9.252819449866993e-0..."

## Extract features

In [13]:
from scipy.stats import skew, kurtosis

In [14]:
def safe_float_convert(value):
    try:
        return float(value)
    except ValueError:
        return np.nan

def parse_column(column_data):
    return np.array([safe_float_convert(x) for x in column_data.split(',')])

def extract_fft_features(window):
    fft = np.fft.fft(window)
    magnitudes = np.abs(fft)
    freqs = np.fft.fftfreq(len(fft), d=1/SAMPLE_RATE)
    magnitudes = magnitudes[freqs >= 0]
    top_5_freq_indices = np.argsort(magnitudes)[::-1][:5]
    top_5_magnitudes = magnitudes[top_5_freq_indices]

    return top_5_magnitudes.tolist()

def extract_features(window):
    mean = np.mean(window)
    std = np.std(window)
    abs_dev = np.mean(np.abs(window - np.mean(window)))
    median = np.median(window)
    median_abs_dev = np.median(np.abs(window - median))
    iqr = np.percentile(window, 75) - np.percentile(window, 25)
    neg_count = np.sum(window < 0)
    pos_count = np.sum(window > 0)
    above_mean_count = np.sum(window > mean)
    num_peaks = len(find_peaks(window)[0])
    energy = np.sum(window ** 2)
    skewness = skew(window)
    kurt = kurtosis(window)
    avg_resultant_acc = np.mean(np.sqrt(window ** 2))
    sma = np.sum(np.abs(window))
    
    features = [mean,
                std,
                abs_dev,
                median,
                median_abs_dev,
                iqr,
                neg_count,
                pos_count,
                above_mean_count,
                num_peaks,
                energy,
                skewness,
                kurt,
                avg_resultant_acc,
                sma]
    
    features += extract_fft_features(window)    
    return features

In [15]:
df['AccXFeatures'] = df['AccX'].apply(lambda x: extract_features(x))
df['AccYFeatures'] = df['AccY'].apply(lambda x: extract_features(x))
df['AccZFeatures'] = df['AccZ'].apply(lambda x: extract_features(x))
df['VelXFeatures'] = df['VelX'].apply(lambda x: extract_features(x))
df['VelYFeatures'] = df['VelY'].apply(lambda x: extract_features(x))
df['VelZFeatures'] = df['VelZ'].apply(lambda x: extract_features(x))
df['PosXFeatures'] = df['PosX'].apply(lambda x: extract_features(x))
df['PosYFeatures'] = df['PosY'].apply(lambda x: extract_features(x))
df['PosZFeatures'] = df['PosZ'].apply(lambda x: extract_features(x))
df['PitchFeatures'] = df['Pitch'].apply(lambda x: extract_features(x))
df['RollFeatures'] = df['Roll'].apply(lambda x: extract_features(x))
df['YawFeatures'] = df['Yaw'].apply(lambda x: extract_features(x))

## Train a exercise classifier

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [17]:
N_ESTIMATORS = 100
MAX_DEPTH = 10  
RANDOM_STATE = 0

In [21]:
for col in ['AccXFeatures', 'AccYFeatures', 'AccZFeatures', 'VelXFeatures', 'VelYFeatures', 'VelZFeatures', 'PosXFeatures', 'PosYFeatures', 'PosZFeatures', 'PitchFeatures', 'RollFeatures', 'YawFeatures']:
    if isinstance(df[col].iloc[0], list):
        df[col] = df[col].apply(lambda x: x[0] if isinstance(x, list) else x)

X = df[['AccXFeatures', 'AccYFeatures', 'AccZFeatures', 'VelXFeatures', 'VelYFeatures', 'VelZFeatures', 'PosXFeatures', 'PosYFeatures', 'PosZFeatures', 'PitchFeatures', 'RollFeatures', 'YawFeatures']]
y = df['Exercise']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE)

clf = RandomForestClassifier(n_estimators=N_ESTIMATORS, max_depth=MAX_DEPTH, random_state=RANDOM_STATE)
clf.fit(X_train, y_train)

print("Training accuracy: ", clf.score(X_train, y_train))
print("Testing accuracy: ", clf.score(X_test, y_test))

y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred, zero_division=0))

Training accuracy:  1.0
Testing accuracy:  0.8431372549019608
                        precision    recall  f1-score   support

            Ab Rollout       0.00      0.00      0.00         1
                 Bench       0.95      0.91      0.93        23
              DB Bench       0.80      1.00      0.89         4
         DB Bicep Curl       1.00      0.67      0.80         3
           DB Deadlift       0.00      0.00      0.00         1
       DB Goblet Squat       1.00      0.50      0.67         2
                DB OHP       0.00      0.00      0.00         2
         DB Side Raise       0.73      1.00      0.84         8
              Deadlift       0.75      0.75      0.75         4
Horizontal Chest Press       1.00      1.00      1.00         5
         Lat Pull-down       0.00      0.00      0.00         1
          Lat Pulldown       0.00      0.00      0.00         2
          Lat pulldown       0.00      0.00      0.00         1
                   OHP       0.85      0.92      0.88        24
              Pull Ups       0.00      0.00      0.00         1
                   Row       0.88      1.00      0.93         7
                 Squat       0.69      1.00      0.81        11
 Tricep Cable Pushdown       1.00      1.00      1.00         2

              accuracy                           0.84       102
             macro avg       0.54      0.54      0.53       102
          weighted avg       0.78      0.84      0.80       102

## Train a predictor for whether is in rep state or non rep state

 For entries with a RepStartTime and RepEndTime
 - Extract windows for each axes
 - Label window with 0 or 1 depending on whether it is between RepStartTime and RepEndTime
 - Create a classifier for this data

In [23]:
# extract windows for each axes

def extract_windows(data, window_size, overlap):
    windows = []
    for i in range(0, len(data) - window_size, window_size - overlap):
        windows.append(data[i:i+window_size])
    return windows

WINDOW_SIZE = 100
OVERLAP = 50

df['AccXWindows'] = df['AccX'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['AccYWindows'] = df['AccY'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['AccZWindows'] = df['AccZ'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['VelXWindows'] = df['VelX'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['VelYWindows'] = df['VelY'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['VelZWindows'] = df['VelZ'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['PosXWindows'] = df['PosX'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['PosYWindows'] = df['PosY'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['PosZWindows'] = df['PosZ'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['PitchWindows'] = df['Pitch'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['RollWindows'] = df['Roll'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))
df['YawWindows'] = df['Yaw'].apply(lambda x: extract_windows(x, WINDOW_SIZE, OVERLAP))

In [ ]:
# extract features for each window

def extract_window_features(window):
    features = []
    for i in range(len(window)):
        features.append(extract_features(window[i]))
    return features

df['AccXWindowFeatures'] = df['AccXWindows'].apply(lambda x: extract_window_features(x))
df['AccYWindowFeatures'] = df['AccYWindows'].apply(lambda x: extract_window_features(x))
df['AccZWindowFeatures'] = df['AccZWindows'].apply(lambda x: extract_window_features(x))
df['VelXWindowFeatures'] = df['VelXWindows'].apply(lambda x: extract_window_features(x))
df['VelYWindowFeatures'] = df['VelYWindows'].apply(lambda x: extract_window_features(x))
df['VelZWindowFeatures'] = df['VelZWindows'].apply(lambda x: extract_window_features(x))
df['PosXWindowFeatures'] = df['PosXWindows'].apply(lambda x: extract_window_features(x))
df['PosYWindowFeatures'] = df['PosYWindows'].apply(lambda x: extract_window_features(x))
df['PosZWindowFeatures'] = df['PosZWindows'].apply(lambda x: extract_window_features(x))
df['PitchWindowFeatures'] = df['PitchWindows'].apply(lambda x: extract_window_features(x))
df['RollWindowFeatures'] = df['RollWindows'].apply(lambda x: extract_window_features(x))
df['YawWindowFeatures'] = df['YawWindows'].apply(lambda x: extract_window_features(x))

In [29]:
import numpy as np
import pandas as pd

# Assuming SAMPLE_RATE is defined
SAMPLE_RATE = 100  # Example value, replace with actual sample rate

# Function to extract time
def extract_time(data, sample_rate):
    return np.cumsum(data) / sample_rate

# Apply the function and create a new DataFrame from the lists
time_df = df['TimeBetweenSamples'].apply(lambda x: pd.Series(extract_time(x, SAMPLE_RATE)))

# Rename the columns of the new DataFrame to avoid conflicts
time_df.columns = [f'Time_{i}' for i in range(time_df.shape[1])]

# Assign the new DataFrame to the original DataFrame
df = pd.concat([df, time_df], axis=1)

In [30]:
df

Empty DataFrame
Columns: [Date, Exercise, Lifter, WorkoutTime, Reps, Weight, Intensity, Notes, StartRepTime, EndRepTime, Counter, TimeBetweenSamples, AccX, AccY, AccZ, Pitch, Roll, Yaw, HeartRate, VelX, VelY, VelZ, PosX, PosY, PosZ, AccXFeatures, AccYFeatures, AccZFeatures, VelXFeatures, VelYFeatures, VelZFeatures, PosXFeatures, PosYFeatures, PosZFeatures, PitchFeatures, RollFeatures, YawFeatures, AccXWindows, AccYWindows, AccZWindows, VelXWindows, VelYWindows, VelZWindows, PosXWindows, PosYWindows, PosZWindows, PitchWindows, RollWindows, YawWindows, Date, Exercise, Lifter, WorkoutTime, Reps, Weight, Intensity, Notes, StartRepTime, EndRepTime, Counter, TimeBetweenSamples, AccX, AccY, AccZ, Pitch, Roll, Yaw, HeartRate, VelX, VelY, VelZ, PosX, PosY, PosZ, AccXFeatures, AccYFeatures, AccZFeatures, VelXFeatures, VelYFeatures, VelZFeatures, PosXFeatures, PosYFeatures, PosZFeatures, PitchFeatures, RollFeatures, YawFeatures, AccXWindows, AccYWindows, AccZWindows, VelXWindows, VelYWindows, VelZWindows, PosXWindows, PosYWindows, PosZWindows, PitchWindows, RollWindows, YawWindows, Time_0, Time_1]
Index: []

[0 rows x 100 columns]