# Bar Path Model

### Training a model for bar path tracking

In [47]:
import numpy as np
import pandas as pd

## Grab data from AirTable

In [48]:
from ast import literal_eval
from pyairtable import Api as airtable_api

In [95]:
CUTOFF_FREQ = 0.1
SAMPLE_RATE = 100

WINDOW_SIZE = 100
STEP_SIZE = 50

N_ESTIMATORS = 100
MAX_DEPTH = 10  
RANDOM_STATE = 0

AIR_TABLE_API_KEY = 'patMswkrKzfHWSG3U.a882cccc6e7709b3a24b42b7f9c0ccd48ed15614f13c54e4d3dbaa55ba8ffffb'
BASE_ID = 'appaCiWbsAFmlkOLF'
TABLE_NAME = 'tblZtbDVHfCaoTnsH'
BASE_URL = 'https://api.airtable.com/v0/'

EXERCISE = 'Bench'
VALID_DATA = 'true'
MIN_REPS = '1'

FORMULA = "AND({ValidData} = 'true', " + \
        "{Exercise} = '" + EXERCISE + "', " + \
        "{StartRepTime} != '', " + \
        "{EndRepTime} != '', " + \
        "{Reps} >= '" + MIN_REPS + "')"

FORMULA

"AND({ValidData} = 'true', {Exercise} = 'Bench', {StartRepTime} != '', {EndRepTime} != '', {Reps} >= '1')"

In [75]:
def to_numpy(data):
    return np.array(literal_eval(data))

def to_float(data):
    return float(data)

In [76]:
api = airtable_api(AIR_TABLE_API_KEY)
table = api.table(BASE_ID, TABLE_NAME)

matches = table.all(formula=FORMULA)
print("Number of matching records: ", len(matches))

Number of matching records:  41

In [77]:
df = pd.DataFrame(columns=[
    'Date',
    'Exercise',
    'Lifter',
    'WorkoutTime',
    'Reps',
    'Weight',
    'Intensity',
    'Notes',
    'StartRepTime',
    'EndRepTime',
    'Counter',
    'TimeBetweenSamples',
    'AccX',
    'AccY',
    'AccZ',
    'Pitch',
    'Roll',
    'Yaw',
    'HeartRate'
])

data_dict = []

for match in matches:
    data = match['fields']
    
    data_dict.append({
        'Date': data.get('Date'),
        'Exercise': data.get('Exercise'),
        'Lifter': data.get('Lifter'),
        'WorkoutTime': data.get('WorkoutTime'),
        'Reps': data.get('Reps'),
        'Weight': data.get('Weight'),
        'Intensity': data.get('Intensity'),
        'Notes': data.get('Notes'),
        'StartRepTime': data.get('StartRepTime'),
        'EndRepTime': data.get('EndRepTime'),
        'Counter': to_numpy(data.get('Counter')),
        'TimeBetweenSamples': to_numpy(data.get('TimeBetweenSamples')),
        'AccX': to_numpy(data.get('AccX')),
        'AccY': to_numpy(data.get('AccY')),
        'AccZ': to_numpy(data.get('AccZ')),
        'Pitch': to_numpy(data.get('Pitch')),
        'Roll': to_numpy(data.get('Roll')),
        'Yaw': to_numpy(data.get('Yaw')),
        'HeartRate': to_numpy(data.get('HeartRate')),
    })

df = pd.concat([pd.DataFrame([d]) for d in data_dict], ignore_index=True)
df

,Date,Exercise,Lifter,WorkoutTime,Reps,Weight,Intensity,Notes,StartRepTime,EndRepTime,Counter,TimeBetweenSamples,AccX,AccY,AccZ,Pitch,Roll,Yaw,HeartRate
0,"Apr 27, 2024 at 10:41:29 AM",Bench,Anwar,35.35,6,205,9,None,13.44,27.93,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[205284, 8, 11, 9, 10, 10, 10, 12, 9, 11, 9, 1...","[0.057, 0.192, 0.262, 0.207, 0.184, 0.111, -0....","[-0.014, 0.239, 0.342, 0.259, 0.248, 0.047, -0...","[0.073, -0.095, -0.129, -0.078, -0.054, -0.009...","[0.383, 0.383, 0.383, 0.383, 0.383, 0.382, 0.3...","[0.041, 0.04, 0.04, 0.04, 0.04, 0.041, 0.04, 0...","[-0.008, -0.007, -0.007, -0.007, -0.008, -0.00...","[88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 8..."
1,"Mar 6, 2024 at 7:00:55 AM",Bench,Anwar,35.75,4,240,10,None,15.04,28.92,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[185403, 9, 13, 9, 8, 10, 10, 10, 10, 10, 10, ...","[-0.055, -0.163, -0.174, 0.001, 0.017, -0.031,...","[-0.172, -0.25, -0.205, -0.101, -0.065, -0.08,...","[0.077, 0.173, 0.187, 0.127, 0.037, -0.014, 0....","[-0.31, -0.31, -0.311, -0.312, -0.312, -0.313,...","[0.209, 0.21, 0.21, 0.21, 0.211, 0.211, 0.212,...","[0.033, 0.033, 0.033, 0.034, 0.034, 0.035, 0.0...","[99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 9..."
2,"Mar 6, 2024 at 6:53:59 AM",Bench,Anwar,29.18,5,225,8,None,13.53,24.54,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[161517, 29, 0, 0, 9, 10, 10, 10, 10, 10, 10, ...","[0.097, 0.129, 0.04, 0.06, 0.111, 0.056, 0.041...","[0.071, -0.012, -0.164, -0.167, -0.11, -0.126,...","[0.185, 0.168, 0.182, 0.242, 0.282, 0.36, 0.47...","[0.42, 0.419, 0.419, 0.418, 0.417, 0.415, 0.41...","[-0.035, -0.035, -0.036, -0.037, -0.038, -0.03...","[0.008, 0.007, 0.007, 0.007, 0.007, 0.007, 0.0...","[80, 80, 80, 80, 80, 80, 81, 81, 81, 81, 81, 8..."
3,"Mar 6, 2024 at 6:50:48 AM",Bench,Anwar,27.94,5,185,5,None,13.95,23.43,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[167543, 9, 10, 11, 9, 11, 9, 10, 10, 10, 10, ...","[0.032, 0.217, 0.169, -0.01, 0.045, 0.196, 0.1...","[0.273, 0.248, 0.152, 0.091, 0.209, 0.219, 0.1...","[0.284, 0.239, 0.126, 0.027, 0.042, 0.055, 0.0...","[-0.249, -0.25, -0.251, -0.251, -0.251, -0.252...","[0.308, 0.308, 0.307, 0.307, 0.306, 0.305, 0.3...","[0.039, 0.039, 0.039, 0.039, 0.04, 0.04, 0.04,...","[112, 112, 112, 112, 112, 112, 112, 112, 112, ..."
4,"Mar 2, 2024 at 2:50:08 PM",Bench,Anwar,26.90,5,205,7,None,13.00,22.62,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[109533, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[0.163, 0.025, -0.14, -0.131, 0.103, 0.198, 0....","[0.14, 0.243, 0.188, 0.056, 0.03, 0.048, -0.02...","[-0.171, -0.186, -0.241, -0.232, -0.162, -0.08...","[0.611, 0.61, 0.611, 0.611, 0.611, 0.611, 0.61...","[0.001, 0.0, 0.0, -0.0, -0.001, -0.001, -0.002...","[-0.0, 0.001, 0.001, 0.002, 0.003, 0.005, 0.00...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ..."
5,"Jun 4, 2024 at 4:32:13 PM",Bench,Anwar,36.65,6,205,8,None,16.88,30.08,"[0, 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[340167980, 1, 9, 9, 10, 10, 10, 11, 9, 10, 10...","[0.007, -0.189, -0.047, 0.089, 0.086, 0.005, -...","[-0.306, 0.044, 0.086, -0.049, -0.097, -0.004,...","[0.174, 0.051, 0.003, 0.129, 0.196, 0.27, 0.21...","[0.218, 0.218, 0.218, 0.217, 0.217, 0.216, 0.2...","[-0.017, -0.017, -0.018, -0.018, -0.018, -0.01...","[0.002, 0.002, 0.002, 0.001, 0.001, 0.001, 0.0...","[89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 8..."
6,"Mar 17, 2024 at 1:43:08 PM",Bench,Anwar,36.49,5,225,9,None,17.11,30.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[162425, 12, 8, 10, 10, 10, 10, 10, 10, 10, 10...","[0.051, -0.059, -0.075, -0.134, -0.059, -0.055...","[0.323, 0.241, 0.198, -0.062, -0.134, -0.027, ...","[-0.135, -0.048, -0.096, 0.03, 0.099, 0.149, 0...","[0.313, 0.315, 0.317, 0.318, 0.319, 0.319, 0.3...","[0.074, 0.074, 0.073, 0.073, 0.072, 0.072, 0.0...","[-0.012, -0.012, -0.013, -0.013, -0.012, -0.01...","[98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 9..."
7,"Apr 20, 2024 at 10:36:11 AM",Bench,Anwar,50.23,6,215,9,None,23.24,39.18,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[146789, 10, 8, 10, 10, 10, 11, 10, 10, 9, 10,...","[0.172, 0.156, 0.116, 0.079, 0.057, 0.072, 0.0...","[0.084, 0.156, 0.079, -0.051, -0.094, -0.092, ...","[0.033, 0.048, 0.048, 0.077, 0.132, 0.176, 0.1...","[0.36, 0.361, 0.361, 0.361, 0.361, 0.362, 0.36...","[0.074, 0.074, 0.074, 0.073, 0.073, 0.072, 0.0...","[-0.014, -0.013, -0.013, -0.013, -0.012, -0.01...","[78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 7..."
8,"Apr 27, 2024 at 10:37:28 AM",Bench,Anwar,27.82,7,135,5,None,12.19,22.79,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[42074, 11, 7, 14, 6, 11, 9, 10, 10, 10, 10, 1...","[-0.166, -0.114, 0.0, -0.04, 0.008, -0.003, 0....","[-0.391, -0.328, -0.153, -0.113, -0.07, -0.038...","[0.345, 0.307, 0.172, 0.071, 0.086, 0.114, 0.0...","[-0.002, -0.005, -0.008, -0.01, -0.013, -0.014...","[0.181, 0.181, 0.182, 0.182, 0.183, 0.184, 0.1...","[0.0, -0.001, -0.001, -0.001, -0.001, -0.001, ...","[120, 120, 120, 120, 120, 120, 120, 120, 120, ..."
9,"Mar 20, 2024 at 6:49:19 AM",Bench,Anwar,37.38,5,225,9,None,18.36,30.29,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[108365, 10, 7, 10, 10, 10, 10, 10, 10, 10, 10...","[0.225, 0.196, 0.025, 0.056, 0.124, 0.181, 0.1...","[0.087, 0.182, -0.141, -0.278, -0.181, -0.132,...","[-0.093, -0.021, 0.004, 0.027, 0.102, 0.126, 0...","[0.611, 0.611, 0.61, 0.609, 0.608, 0.607, 0.60...","[0.023, 0.022, 0.021, 0.021, 0.02, 0.019, 0.01...","[-0.007, -0.007, -0.008, -0.008, -0.008, -0.00...","[95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 9..."
10,"Apr 23, 2024 at 6:49:03 AM",Bench,Anwar,44.42,8,185,9,None,16.59,37.31,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[151001, 12, 8, 10, 10, 10, 11, 9, 11, 9, 10, ...","[-0.082, 0.004, -0.147, -0.148, 0.045, 0.129, ...","[0.078, -0.069, -0.09, -0.126, -0.193, -0.24, ...","[-0.069, -0.108, -0.007, 0.156, 0.295, 0.284, ...","[-0.196, -0.195, -0.194, -0.194, -0.195, -0.19...","[0.172, 0.172, 0.173, 0.173, 0.174, 0.175, 0.1...","[0.017, 0.017, 0.017, 0.017, 0.017, 0.018, 0.0...","[138, 138, 138, 138, 138, 138, 138, 138, 138, ..."
11,"Mar 20, 2024 at 6:57:06 AM",Bench,Anwar,47.05,4,225,10,None,30.11,40.6,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[185077, 14, 7, 10, 7, 10, 11, 9, 13, 8, 8, 10...","[-0.024, -0.031, 0.016, 0.08, 0.033, -0.056, -...","[0.039, 0.056, 0.038, 0.096, 0.105, 0.02, 0.04...","[0.015, -0.08, -0.057, -0.09, -0.11, -0.08, -0...","[-0.276, -0.276, -0.276, -0.276, -0.276, -0.27...","[0.298, 0.297, 0.297, 0.297, 0.296, 0.296, 0.2...","[0.042, 0.041, 0.041, 0.041, 0.041, 0.041, 0.0...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ..."
12,"Apr 20, 2024 at 10:32:54 AM",Bench,Anwar,39.02,6,215,9,None,17.56,31.14,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[141650468, 0, 6, 10, 9, 10, 10, 10, 11, 9, 10...","[0.01, 0.041, -0.013, -0.023, -0.038, -0.023, ...","[-0.097, -0.012, 0.048, -0.035, -0.086, -0.054...","[-0.018, -0.019, 0.032, 0.052, 0.087, 0.074, 0...","[-0.283, -0.283, -0.283, -0.283, -0.283, -0.28...","[0.227, 0.226, 0.225, 0.225, 0.225, 0.226, 0.2...","[0.032, 0.032, 0.032, 0.032, 0.032, 0.032, 0.0...","[80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 8..."
13,"Mar 17, 2024 at 1:39:49 PM",Bench,Anwar,37.01,5,225,8,None,18.62,31.3,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[119670, 11, 8, 10, 10, 10, 10, 10, 10, 10, 10...","[0.284, 0.103, -0.053, -0.051, -0.002, 0.231, ...","[0.609, 0.166, -0.23, -0.169, 0.168, 0.348, -0...","[0.076, -0.001, -0.029, 0.074, 0.215, 0.169, 0...","[0.862, 0.863, 0.864, 0.863, 0.862, 0.861, 0.8...","[-0.069, -0.071, -0.073, -0.072, -0.068, -0.06...","[0.032, 0.035, 0.037, 0.037, 0.034, 0.028, 0.0...","[87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 8..."
14,"Apr 20, 2024 at 10:45:07 AM",Bench,Anwar,40.71,9,175,9,None,13.67,34.39,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[240052, 7, 9, 9, 11, 9, 10, 11, 9, 10, 10, 10...","[0.187, 0.064, -0.338, -0.446, -0.245, -0.096,...","[0.201, -0.055, -0.188, -0.221, -0.185, -0.041...","[-0.263, -0.105, 0.123, 0.298, 0.252, 0.215, 0...","[1.012, 1.012, 1.012, 1.013, 1.014, 1.016, 1.0...","[-2.097, -2.103, -2.106, -2.108, -2.108, -2.10...","[2.524, 2.531, 2.535, 2.538, 2.539, 2.539, 2.5...","[116, 116, 116, 116, 116, 116, 116, 116, 116, ..."
15,"Mar 29, 2024 at 11:30:42 AM",Bench,Anwar,38.93,3,245,10,None,18.62,27.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[179036, 14, 4, 10, 10, 10, 10, 9, 10, 10, 10,...","[0.251, 0.187, -0.054, -0.057, 0.089, 0.04, 0....","[0.052, 0.2, 0.052, -0.144, -0.136, -0.097, -0...","[-0.063, -0.066, 0.003, 0.082, 0.064, 0.098, 0...","[0.352, 0.353, 0.355, 0.356, 0.357, 0.356, 0.3...","[0.019, 0.017, 0.016, 0.015, 0.015, 0.017, 0.0...","[-0.003, -0.003, -0.003, -0.002, -0.002, -0.00...","[82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 8..."
16,"Mar 2, 2024 at 3:02:48 PM",Bench,Anwar,38.83,5,235,10,None,14.82,31.70,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[222047, 10, 11, 10, 10, 10, 10, 10, 11, 9, 10...","[-0.069, 0.021, 0.044, 0.032, 0.21, -0.381, -0...","[0.145, 0.199, 0.076, -0.105, -0.312, -0.367, ...","[0.235, 0.178, 0.126, 0.124, 0.203, 0.32, 0.35...","[0.122, 0.12, 0.117, 0.114, 0.111, 0.109, 0.10...","[0.131, 0.131, 0.131, 0.129, 0.129, 0.129, 0.1...","[-0.008, -0.008, -0.01, -0.012, -0.018, -0.022...","[108, 108, 108, 108, 108, 108, 108, 108, 108, ..."
17,"Mar 2, 2024 at 2:58:28 PM",Bench,Anwar,36.47,5,235,9,None,16.30,29.79,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[251287, 10, 10, 10, 10, 11, 11, 9, 9, 10, 10,...","[-0.221, -0.205, -0.003, 0.038, -0.059, -0.031...","[0.098, 0.262, 0.505, 0.478, 0.265, 0.132, 0.0...","[0.021, -0.095, -0.204, -0.183, -0.155, -0.067...","[-0.442, -0.441, -0.439, -0.437, -0.435, -0.43...","[0.266, 0.267, 0.267, 0.267, 0.267, 0.267, 0.2...","[0.06, 0.061, 0.061, 0.061, 0.06, 0.06, 0.06, ...","[108, 108, 108, 108, 108, 108, 108, 108, 108, ..."
18,"Mar 17, 2024 at 1:46:35 PM",Bench,Anwar,42.65,5,225,10,None,21.86,35.71,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[164100, 11, 9, 10, 10, 10, 10, 10, 10, 10, 10...","[0.868, 0.971, 0.735, 0.309, 0.107, -0.084, -0...","[1.456, 1.642, 1.013, 0.131, -0.244, -0.627, -...","[-0.321, -0.512, -0.569, -0.144, 0.163, 0.259,...","[0.531, 0.531, 0.531, 0.529, 0.524, 0.516, 0.5...","[0.08, 0.079, 0.078, 0.077, 0.077, 0.076, 0.07...","[-0.022, -0.023, -0.026, -0.029, -0.033, -0.03...","[109, 109, 109, 109, 109, 109, 109, 109, 109, ..."
19,"Mar 6, 2024 at 7:04:58 AM",Bench,Anwar,34.93,5,225,9,None,16.37,29.12,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[208552, 0, 0, 0, 2, 10, 10, 10, 10, 10, 10, 1...","[0.013, 0.107, 0.225, 0.112, -0.028, -0.02, -0...","[0.071, 0.146, 0.043, -0.129, -0.307, -0.276, ...","[0.01, 0.029, 0.065, 0.137, 0.15, 0.162, 0.171...","[0.318, 0.319, 0.32, 0.321, 0.322, 0.322, 0.32...","[-0.073, -0.074, -0.074, -0.074, -0.075, -0.07...","[0.012, 0.012, 0.012, 0.011, 0.012, 0.012, 0.0...","[80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 8..."
20,"Jun 4, 2024 at 4:39:47 PM",Bench,Anwar,34.06,5,215,10,None,13.59,26.66,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[211939, 13, 7, 10, 10, 10, 10, 10, 11, 9, 10,...","[0.071, 0.05, -0.113, -0.366, -0.524, -0.433, ...","[0.075, 0.097, -0.114, -0.362, -0.498, -0.547,...","[-0.457, -0.213, -0.034, 0.086, 0.223, 0.219, ...","[0.679, 0.677, 0.675, 0.674, 0.674, 0.675, 0.6...","[-2.747, -2.75, -2.752, -2.753, -2.753, -2.752...","[3.001, 3.002, 3.004, 3.006, 3.007, 3.008, 3.0...","[119, 119, 119, 119, 119, 119, 119, 119, 119, ..."
21,"Mar 20, 2024 at 6:46:54 AM",Bench,Anwar,32.89,5,205,7,None,17.86,27.16,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[99476, 13, 17, 0, 9, 10, 9, 10, 10, 10, 10, 1...","[-0.01, 0.031, -0.072, 0.006, 0.153, 0.189, 0....","[-0.049, 0.239, 0.068, -0.131, -0.041, -0.001,...","[-0.167, -0.398, -0.431, -0.327, -0.173, 0.066...","[-0.179, -0.179, -0.178, -0.178, -0.178, -0.17...","[0.12, 0.12, 0.121, 0.122, 0.123, 0.123, 0.124...","[0.011, 0.01, 0.008, 0.008, 0.007, 0.006, 0.00...","[95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 9..."
22,"Mar 29, 2024 at 11:27:04 AM",Bench,Anwar,32.12,3,245,10,None,12.69,22.56,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[165534, 11, 7, 10, 11, 9, 11, 9, 10, 10, 10, ...","[0.079, 0.128, 0.065, -0.088, 0.023, -0.078, -...","[0.588, 0.328, -0.18, -0.371, -0.61, -0.627, -...","[0.163, -0.24, -0.168, -0.108, -0.143, 0.101, ...","[0.727, 0.728, 0.731, 0.735, 0.74, 0.744, 0.74...","[-2.728, -2.727, -2.726, -2.725, -2.723, -2.72...","[2.982, 2.982, 2.981, 2.979, 2.976, 2.972, 2.9...","[94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 9..."
23,"Apr 13, 2024 at 9:23:38 AM",Bench,Anwar,36.61,5,225,9,None,18.35,29.11,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[244049, 0, 5, 11, 7, 10, 11, 9, 10, 10, 10, 1...","[-0.275, -0.13, 0.073, 0.21, 0.157, 0.015, -0....","[0.005, -0.057, -0.041, 0.058, 0.053, -0.052, ...","[-0.0, -0.086, -0.056, -0.033, 0.034, 0.139, 0...","[0.211, 0.212, 0.212, 0.212, 0.213, 0.213, 0.2...","[0.081, 0.081, 0.08, 0.079, 0.079, 0.079, 0.07...","[-0.009, -0.008, -0.008, -0.007, -0.006, -0.00...","[91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 9..."
24,"Apr 27, 2024 at 10:50:24 AM",Bench,Anwar,49.39,4,205,9,None,22.17,34.02,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[217326, 11, 8, 10, 10, 10, 10, 10, 11, 10, 10...","[-0.333, -0.173, 0.079, 0.171, 0.156, 0.015, -...","[-0.293, -0.35, -0.093, 0.098, 0.116, 0.043, 0...","[0.247, 0.068, -0.128, -0.138, -0.048, 0.052, ...","[0.309, 0.307, 0.307, 0.307, 0.307, 0.306, 0.3...","[0.11, 0.11, 0.109, 0.108, 0.107, 0.108, 0.108...","[-0.017, -0.016, -0.015, -0.015, -0.014, -0.01...","[107, 107, 107, 107, 107, 107, 107, 107, 107, ..."
25,"Mar 20, 2024 at 6:53:14 AM",Bench,Anwar,37.64,5,225,10,None,15.84,30.52,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[197173, 11, 7, 10, 9, 10, 11, 9, 11, 9, 11, 1...","[0.106, 0.157, -0.133, -0.094, 0.035, -0.061, ...","[0.019, -0.048, -0.013, -0.111, -0.143, -0.104...","[0.006, -0.129, -0.028, 0.073, 0.024, 0.047, 0...","[0.195, 0.196, 0.196, 0.196, 0.196, 0.195, 0.1...","[0.022, 0.02, 0.02, 0.019, 0.019, 0.02, 0.02, ...","[-0.002, -0.0, 0.002, 0.003, 0.004, 0.005, 0.0...","[87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 8..."
26,"Jun 4, 2024 at 4:35:41 PM",Bench,Anwar,44.89,5,215,9,None,22,36.06,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[163217, 12, 9, 8, 9, 10, 11, 9, 11, 9, 12, 9,...","[-0.097, -0.3, -0.079, 0.266, 0.148, -0.058, -...","[-0.279, -0.205, 0.095, 0.07, 0.018, 0.016, -0...","[0.063, 0.008, -0.113, -0.017, 0.077, 0.191, 0...","[0.566, 0.565, 0.564, 0.564, 0.565, 0.564, 0.5...","[-0.041, -0.042, -0.043, -0.044, -0.044, -0.04...","[0.012, 0.013, 0.013, 0.014, 0.015, 0.015, 0.0...","[91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 9..."
27,"Mar 20, 2024 at 6:44:41 AM",Bench,Anwar,37.03,8,135,5,None,17.13,30.44,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[231741752, 0, 10, 11, 8, 12, 11, 13, 9, 9, 10...","[-0.137, -0.12, -0.139, -0.144, -0.143, -0.192...","[-0.131, -0.143, -0.187, -0.115, -0.007, -0.00...","[-0.006, -0.013, 0.004, 0.005, -0.04, -0.075, ...","[-0.425, -0.424, -0.424, -0.424, -0.424, -0.42...","[0.348, 0.348, 0.348, 0.348, 0.348, 0.348, 0.3...","[0.076, 0.076, 0.076, 0.077, 0.077, 0.077, 0.0...","[115, 115, 115, 115, 115, 115, 115, 115, 115, ..."
28,"Mar 17, 2024 at 1:37:12 PM",Bench,Anwar,24.60,5,205,7,None,10.73,20.54,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[88531, 10, 10, 10, 11, 10, 10, 10, 10, 10, 10...","[0.684, 0.808, 0.298, 0.004, -0.064, -0.386, -...","[0.755, 0.502, 0.066, -0.347, -0.604, -0.519, ...","[-0.126, 0.006, 0.159, 0.521, 0.493, 0.683, 0....","[0.62, 0.619, 0.616, 0.61, 0.601, 0.591, 0.583...","[-0.021, -0.022, -0.021, -0.021, -0.019, -0.01...","[0.007, 0.007, 0.008, 0.011, 0.013, 0.018, 0.0...","[107, 107, 107, 107, 107, 107, 107, 107, 107, ..."
29,"Apr 27, 2024 at 10:45:57 AM",Bench,Anwar,40.81,5,205,8,None,22.06,34.11,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[227936, 9, 10, 10, 12, 8, 13, 6, 10, 10, 10, ...","[-0.333, -0.352, -0.219, -0.092, -0.057, -0.04...","[-0.187, -0.17, -0.097, 0.093, 0.091, -0.294, ...","[0.071, -0.019, -0.063, -0.036, -0.021, 0.094,...","[-0.127, -0.127, -0.127, -0.127, -0.129, -0.13...","[0.255, 0.254, 0.254, 0.253, 0.253, 0.253, 0.2...","[0.016, 0.015, 0.015, 0.015, 0.016, 0.016, 0.0...","[105, 105, 105, 105, 105, 105, 105, 105, 105, ..."
30,"Jun 4, 2024 at 4:44:20 PM",Bench,Anwar,47.34,8,185,9,None,17.94,38.00,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[225758, 11, 8, 8, 10, 10, 12, 8, 10, 10, 10, ...","[-0.376, -0.254, 0.007, 0.133, 0.101, -0.002, ...","[0.052, 0.087, 0.076, 0.001, 0.035, 0.046, 0.0...","[0.05, -0.007, 0.039, 0.048, 0.049, 0.079, 0.1...","[0.301, 0.301, 0.301, 0.302, 0.302, 0.302, 0.3...","[0.004, 0.004, 0.004, 0.003, 0.002, 0.002, 0.0...","[-0.001, 0.0, 0.001, 0.002, 0.003, 0.004, 0.00...","[96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 9..."
31,"Apr 20, 2024 at 10:40:27 AM",Bench,Anwar,46.73,5,215,9,None,23.48,37.6,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[208538, 12, 8, 10, 11, 8, 10, 10, 10, 11, 8, ...","[-0.04, -0.068, -0.094, -0.121, -0.175, -0.23,...","[0.04, 0.038, 0.104, 0.051, -0.013, -0.01, -0....","[0.025, 0.209, 0.101, -0.005, -0.083, -0.088, ...","[-0.408, -0.407, -0.407, -0.407, -0.408, -0.40...","[0.226, 0.225, 0.224, 0.223, 0.222, 0.221, 0.2...","[0.047, 0.045, 0.043, 0.041, 0.039, 0.036, 0.0...","[105, 105, 105, 105, 105, 105, 105, 105, 105, ..."
32,"Apr 27, 2024 at 10:54:44 AM",Bench,Anwar,40.65,9,155,8,Lost count of reps could be 8 or 10 too,16.01,34.46,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[219526, 11, 11, 9, 8, 11, 9, 10, 12, 8, 10, 1...","[0.198, 0.143, -0.024, -0.086, 0.03, 0.051, -0...","[0.207, 0.128, -0.149, -0.135, 0.052, 0.087, 0...","[-0.034, 0.016, 0.079, 0.032, -0.047, -0.076, ...","[-0.111, -0.112, -0.113, -0.114, -0.114, -0.11...","[0.285, 0.285, 0.285, 0.285, 0.285, 0.285, 0.2...","[0.016, 0.016, 0.017, 0.018, 0.019, 0.02, 0.02...","[107, 107, 107, 107, 107, 107, 107, 107, 107, ..."
33,"Mar 6, 2024 at 6:57:14 AM",Bench,Anwar,32.47,4,240,9,None,15.82,26.75,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[162076, 10, 11, 9, 9, 10, 10, 10, 11, 9, 13, ...","[-0.005, 0.077, 0.056, 0.027, 0.036, 0.085, 0....","[0.193, 0.196, 0.135, 0.083, 0.006, 0.081, 0.1...","[-0.138, -0.16, -0.137, -0.056, 0.054, 0.115, ...","[0.2, 0.201, 0.203, 0.204, 0.204, 0.205, 0.205...","[0.095, 0.095, 0.095, 0.094, 0.094, 0.093, 0.0...","[-0.01, -0.009, -0.009, -0.009, -0.009, -0.008...","[81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 8..."
34,"Mar 2, 2024 at 2:47:52 PM",Bench,Anwar,29.97,10,135,5,None,10.27,24.09,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[146753, 10, 10, 10, 10, 11, 17, 6, 7, 8, 10, ...","[0.057, 0.084, 0.123, 0.104, 0.064, 0.086, 0.0...","[0.194, 0.211, 0.199, 0.192, 0.097, 0.003, 0.0...","[-0.081, -0.064, -0.093, -0.095, -0.045, -0.01...","[0.541, 0.541, 0.542, 0.542, 0.542, 0.541, 0.5...","[0.097, 0.097, 0.096, 0.095, 0.094, 0.093, 0.0...","[-0.027, -0.027, -0.026, -0.025, -0.024, -0.02...","[114, 114, 114, 114, 114, 114, 114, 114, 114, ..."
35,"Apr 23, 2024 at 6:52:58 AM",Bench,Anwar,48.39,8,185,9,None,18.59,37.38,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[186887, 13, 7, 9, 10, 10, 10, 10, 10, 10, 10,...","[-0.139, 0.201, 0.144, 0.156, 0.148, 0.156, 0....","[-0.228, -0.288, -0.154, -0.125, -0.084, -0.10...","[0.167, 0.12, 0.168, 0.257, 0.289, 0.286, 0.24...","[-0.022, -0.022, -0.023, -0.025, -0.027, -0.02...","[0.223, 0.222, 0.221, 0.221, 0.22, 0.219, 0.21...","[0.002, 0.002, 0.002, 0.001, -0.001, -0.002, -...","[130, 130, 130, 130, 130, 130, 130, 130, 130, ..."

## Filter and integrate

In [78]:
from scipy.integrate import cumulative_trapezoid
from scipy.signal import find_peaks, filtfilt, butter

In [80]:
def filter(data, cutoff_freq, sample_rate):
    b, a = butter(1, 2 * cutoff_freq / (sample_rate), btype="highpass")
    return filtfilt(b, a, data)

In [81]:
df['AccX'] = df['AccX'].apply(lambda x: filter(x, CUTOFF_FREQ, SAMPLE_RATE))
df['AccY'] = df['AccY'].apply(lambda x: filter(x, CUTOFF_FREQ, SAMPLE_RATE))
df['AccZ'] = df['AccZ'].apply(lambda x: filter(x, CUTOFF_FREQ, SAMPLE_RATE))

df['VelX'] = df['AccX'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['VelY'] = df['AccY'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['VelZ'] = df['AccZ'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))

df['PosX'] = df['VelX'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['PosY'] = df['VelY'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))
df['PosZ'] = df['VelZ'].apply(lambda x: cumulative_trapezoid(x, dx=1/SAMPLE_RATE))

df

,Date,Exercise,Lifter,WorkoutTime,Reps,Weight,Intensity,Notes,StartRepTime,EndRepTime,...,Pitch,Roll,Yaw,HeartRate,VelX,VelY,VelZ,PosX,PosY,PosZ
0,"Apr 27, 2024 at 10:41:29 AM",Bench,Anwar,35.35,6,205,9,None,13.44,27.93,...,"[0.383, 0.383, 0.383, 0.383, 0.383, 0.382, 0.3...","[0.041, 0.04, 0.04, 0.04, 0.04, 0.041, 0.04, 0...","[-0.008, -0.007, -0.007, -0.007, -0.008, -0.00...","[88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 8...","[-0.003195888462468312, -0.0053848632470395175...","[-0.0023192858278520134, -0.00286637489803972,...","[-0.002395584962981559, -0.005808193964378528,...","[-4.2903758547539145e-05, -0.00010741317552610...","[-2.592830362945867e-05, -5.68667050713439e-05...","[-4.101889463680043e-05, -0.000115774619075771..."
1,"Mar 6, 2024 at 7:00:55 AM",Bench,Anwar,35.75,4,240,10,None,15.04,28.92,...,"[-0.31, -0.31, -0.311, -0.312, -0.312, -0.313,...","[0.209, 0.21, 0.21, 0.21, 0.211, 0.211, 0.212,...","[0.033, 0.033, 0.033, 0.034, 0.034, 0.035, 0.0...","[99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 9...","[-0.007841385873689807, -0.01632887224661385, ...","[-0.0024064690738754254, -0.00499308504834592,...","[-0.002820559592569354, -0.005108135793820296,...","[-0.00012085129060151828, -0.00032273455299006...","[-3.6997770611106724e-05, -9.621290114838193e-...","[-3.9643476931948246e-05, -0.00010339828896877..."
2,"Mar 6, 2024 at 6:53:59 AM",Bench,Anwar,29.18,5,225,8,None,13.53,24.54,...,"[0.42, 0.419, 0.419, 0.418, 0.417, 0.415, 0.41...","[-0.035, -0.035, -0.036, -0.037, -0.038, -0.03...","[0.008, 0.007, 0.007, 0.007, 0.007, 0.007, 0.0...","[80, 80, 80, 80, 80, 80, 81, 81, 81, 81, 81, 8...","[-0.008654192213433094, -0.01764551417892527, ...","[-0.003445087329499873, -0.008064759736085645,...","[-0.0026576431597704, -0.005364412911090466, -...","[-0.00013149853196179183, -0.00035489771014474...","[-5.754923532792759e-05, -0.000165169012269391...","[-4.011028035430433e-05, -0.000105609406483978..."
3,"Mar 6, 2024 at 6:50:48 AM",Bench,Anwar,27.94,5,185,5,None,13.95,23.43,...,"[-0.249, -0.25, -0.251, -0.251, -0.251, -0.252...","[0.308, 0.308, 0.307, 0.307, 0.306, 0.305, 0.3...","[0.039, 0.039, 0.039, 0.039, 0.04, 0.04, 0.04,...","[112, 112, 112, 112, 112, 112, 112, 112, 112, ...","[-1.9349340328203638e-05, 0.000634104017285472...","[-0.001055613463099274, -0.0027166669876206246...","[-0.0007411546566765374, -0.002260759270630684...","[3.073773384786344e-06, 6.946133009185864e-06,...","[-1.8861402253599493e-05, -5.826087682652995e-...","[-1.500956963653611e-05, -5.045774848604877e-0..."
4,"Mar 2, 2024 at 2:50:08 PM",Bench,Anwar,26.90,5,205,7,None,13.00,22.62,...,"[0.611, 0.61, 0.611, 0.611, 0.611, 0.611, 0.61...","[0.001, 0.0, 0.0, -0.0, -0.001, -0.001, -0.002...","[-0.0, 0.001, 0.001, 0.002, 0.003, 0.005, 0.00...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[-0.00172886797983311, -0.004979273183221311, ...","[-0.0005459052611392812, -0.000848742559796294...","[-0.00023878220378011446, -0.00083529769310464...","[-3.35407058152721e-05, -0.0001035187551256329...","[-6.97323910467788e-06, -2.1634629147064263e-0...","[-5.37039948442379e-06, -1.7894732117329768e-0..."
5,"Jun 4, 2024 at 4:32:13 PM",Bench,Anwar,36.65,6,205,8,None,16.88,30.08,...,"[0.218, 0.218, 0.218, 0.217, 0.217, 0.216, 0.2...","[-0.017, -0.017, -0.018, -0.018, -0.018, -0.01...","[0.002, 0.002, 0.002, 0.001, 0.001, 0.001, 0.0...","[89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 8...","[-0.0039493686193578055, -0.008184311621794938...","[-0.0008618083887122424, 0.0002007887673182201...","[-0.0005330117004746367, -0.001922872767692140...","[-6.066840120576372e-05, -0.000156814858390224...","[-3.3050981069701115e-06, 1.5128931508776925e-...","[-1.2279422340833886e-05, -3.651691510035014e-..."
6,"Mar 17, 2024 at 1:43:08 PM",Bench,Anwar,36.49,5,225,9,None,17.11,30.2,...,"[0.313, 0.315, 0.317, 0.318, 0.319, 0.319, 0.3...","[0.074, 0.074, 0.073, 0.073, 0.072, 0.072, 0.0...","[-0.012, -0.012, -0.013, -0.013, -0.012, -0.01...","[98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 9...","[-0.003635486965999579, -0.007908948991860048,...","[-0.002217037757322785, -0.005050707657932616,...","[-0.0004530561783422571, -0.00073382313393828,...","[-5.7722179789298135e-05, -0.00016009468611402...","[-3.633872707627701e-05, -0.000108547917148769...","[-5.934396561402686e-06, -1.2840062364099117e-..."
7,"Apr 20, 2024 at 10:36:11 AM",Bench,Anwar,50.23,6,215,9,None,23.24,39.18,...,"[0.36, 0.361, 0.361, 0.361, 0.361, 0.362, 0.36...","[0.074, 0.074, 0.074, 0.073, 0.073, 0.072, 0.0...","[-0.014, -0.013, -0.013, -0.013, -0.012, -0.01...","[78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 7...","[-0.0016872211691141997, -0.003657534386146733...","[-0.0013686132498129857, -0.002764051889999622...","[-0.00033573427489250174, -0.00060764614395729...","[-2.6723777776304663e-05, -7.50915420747915e-0...","[-2.066332569906304e-05, -6.0465490047260717e-...","[-4.7169020942489666e-06, -1.1483861069723402e..."
8,"Apr 27, 2024 at 10:37:28 AM",Bench,Anwar,27.82,7,135,5,None,12.19,22.79,...,"[-0.002, -0.005, -0.008, -0.01, -0.013, -0.014...","[0.181, 0.181, 0.182, 0.182, 0.183, 0.184, 0.1...","[0.0, -0.001, -0.001, -0.001, -0.001, -0.001, ...","[120, 120, 120, 120, 120, 120, 120, 120, 120, ...","[-0.001970443119128024, -0.003136564377599401,...","[-0.0007020655198504217, -0.000239575924282374...","[6.240655890714735e-05, -0.000722443818571592,...","[-2.5535037483637127e-05, -6.100993113606484e-...","[-4.708207220663981e-06, 4.563427096176429e-07...","[-3.3001862983222234e-06, -2.0260331524047133e..."
9,"Mar 20, 2024 at 6:49:19 AM",Bench,Anwar,37.38,5,225,9,None,18.36,30.29,...,"[0.611, 0.611, 0.61, 0.609, 0.608, 0.607, 0.60...","[0.023, 0.022, 0.021, 0.021, 0.02, 0.019, 0.01...","[-0.007, -0.007, -0.008, -0.008, -0.008, -0.00...","[95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 9...","[-0.0018184231360385411, -0.004645505331060309...","[-0.0008235117942706353, -0.002778605533835088...","[0.0009488246376420095, 0.002372494614122692, ...","[-3.231964233549425e-05, -9.645394516430927e-0...","[-1.8010586640528617e-05, -6.703046357420177e-...","[1.6606596258823508e-05, 4.859938791199493e-05..."
10,"Apr 23, 2024 at 6:49:03 AM",Bench,Anwar,44.42,8,185,9,None,16.59,37.31,...,"[-0.196, -0.195, -0.194, -0.194, -0.195, -0.19...","[0.172, 0.172, 0.173, 0.173, 0.174, 0.175, 0.1...","[0.017, 0.017, 0.017, 0.017, 0.017, 0.018, 0.0...","[138, 138, 138, 138, 138, 138, 138, 138, 138, ...","[-0.0018940427839250374, -0.004135456467573795...","[-0.0019541073586125243, -0.004739050820370591...","[-0.0002555154373285158, -0.000215703982487488...","[-3.014749625749416e-05, -8.662144776144225e-0...","[-3.346579089491558e-05, -9.616071926938452e-0...","[-2.3560970990800204e-06, 2.2126125120155167e-..."
11,"Mar 20, 2024 at 6:57:06 AM",Bench,Anwar,47.05,4,225,10,None,30.11,40.6,...,"[-0.276, -0.276, -0.276, -0.276, -0.276, -0.27...","[0.298, 0.297, 0.297, 0.297, 0.296, 0.296, 0.2...","[0.042, 0.041, 0.041, 0.041, 0.041, 0.041, 0.0...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[-0.0011157182891888668, -0.002037342267145191...","[0.0006409831480705628, 0.0012800040452118542,...","[-0.0016226261017608479, -0.003604996539197063...","[-1.5765302781670293e-05, -3.8001538192179046e...","[9.604935966412084e-06, 2.6615405905845734e-05...","[-2.6138113204789556e-05, -7.234902847485632e-..."
12,"Apr 20, 2024 at 10:32:54 AM",Bench,Anwar,39.02,6,215,9,None,17.56,31.14,...,"[-0.283, -0.283, -0.283, -0.283, -0.283, -0.28...","[0.227, 0.226, 0.225, 0.225, 0.225, 0.226, 0.2...","[0.032, 0.032, 0.032, 0.032, 0.032, 0.032, 0.0...","[80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 8...","[-0.0029616477378631625, -0.006057228592912722...","[-0.0014871700668497492, -0.002265193836399808...","[0.00031524988594054145, 0.0008770138512964585...","[-4.5094381653879424e-05, -0.00012283985861391...","[-1.8761819516247787e-05, -4.595834027278074e-...","[5.961318686185e-06, 1.9297963494219753e-05, 4..."
13,"Mar 17, 2024 at 1:39:49 PM",Bench,Anwar,37.01,5,225,8,None,18.62,31.3,...,"[0.862, 0.863, 0.864, 0.863, 0.862, 0.861, 0.8...","[-0.069, -0.071, -0.073, -0.072, -0.068, -0.06...","[0.032, 0.035, 0.037, 0.037, 0.034, 0.028, 0.0...","[87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 8...","[-0.0005726407646016904, -0.002835886006398628...","[-0.003607173782006948, -0.011372043138276472,...","[-0.0003159334646633929, -0.001156771624406278...","[-1.704263385500159e-05, -6.05961441138187e-05...","[-7.48960846014171e-05, -0.0002356307490267694...","[-7.363525445348355e-06, -2.1260077527102898e-..."
14,"Apr 20, 2024 at 10:45:07 AM",Bench,Anwar,40.71,9,175,9,None,13.67,34.39,...,"[1.012, 1.012, 1.012, 1.013, 1.014, 1.016, 1.0...","[-2.097, -2.103, -2.106, -2.108, -2.108, -2.10...","[2.524, 2.531, 2.535, 2.538, 2.539, 2.539, 2.5...","[116, 116, 116, 116, 116, 116, 116, 116, 116, ...","[-0.00305710909489139, -0.00873416481914752, -...","[-0.001428516959898356, -0.0047884074620282, -...","[0.0016444437352079828, 0.005201247624912732, ...","[-5.895636957019455e-05, -0.000187409146452928...","[-3.1084622109632786e-05, -9.985062515448318e-...","[3.4228456800603574e-05, 0.0001140124595618848..."
15,"Mar 29, 2024 at 11:30:42 AM",Bench,Anwar,38.93,3,245,10,None,18.62,27.2,...,"[0.352, 0.353, 0.355, 0.356, 0.357, 0.356, 0.3...","[0.019, 0.017, 0.016, 0.015, 0.015, 0.017, 0.0...","[-0.003, -0.003, -0.003, -0.002, -0.002, -0.00...","[82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 8...","[-0.0026446313221176, -0.0068166171146251, -0....","[-0.0018221015073605611, -0.003653096488206381...","[-0.0013265536969514751, -0.002341424988034050...","[-4.73062421837135e-05, -0.0001424449231235905...","[-2.7375989977834713e-05, -8.17068434414157e-0...","[-1.833989342492763e-05, -4.3220267829173197e-..."
16,"Mar 2, 2024 at 3:02:48 PM",Bench,Anwar,38.83,5,235,10,None,14.82,31.70,...,"[0.122, 0.12, 0.117, 0.114, 0.111, 0.109, 0.10...","[0.131, 0.131, 0.131, 0.129, 0.129, 0.129, 0.1...","[-0.008, -0.008, -0.01, -0.012, -0.018, -0.022...","[108, 108, 108, 108, 108, 108, 108, 108, 108, ...","[-0.007185202737732821, -0.013804903669919572,...","[-0.0030787378365000877, -0.006478447282322569...","[0.0004897428631161554, 0.0004323602020064808,...","[-0.00010495053203826196, -0.00027582189623664...","[-4.778592559411328e-05, -0.000137049532764728...","[4.610515325613181e-06, 7.2865786628601346e-06..."
17,"Mar 2, 2024 at 2:58:28 PM",Bench,Anwar,36.47,5,235,9,None,16.30,29.79,...,"[-0.442, -0.441, -0.439, -0.437, -0.435, -0.43...","[0.266, 0.267, 0.267, 0.267, 0.267, 0.267, 0.2...","[0.06, 0.061, 0.061, 0.061, 0.06, 0.06, 0.06, ...","[108, 108, 108, 108, 108, 108, 108, 108, 108, ...","[-0.0035212464751125283, -0.00599081205056121,...","[0.0009063530789809767, 0.003848219764154425, ...","[-0.0013926008191598811, -0.003908146742925714...","[-4.7560292628368686e-05, -0.00011393331782502...","[2.377286421567701e-05, 8.23674968966746e-05, ...","[-2.6503737810427978e-05, -8.035312313462336e-..."
18,"Mar 17, 2024 at 1:46:35 PM",Bench,Anwar,42.65,5,225,10,None,21.86,35.71,...,"[0.531, 0.531, 0.531, 0.529, 0.524, 0.516, 0.5...","[0.08, 0.079, 0.078, 0.077, 0.077, 0.076, 0.07...","[-0.022, -0.023, -0.026, -0.029, -0.033, -0.03...","[109, 109, 109, 109, 109, 109, 109, 109, 109, ...","[-0.0030468640894983413, -0.006704949225182481...","[-0.006435933654952021, -0.01496682010515978, ...","[-0.0006354677810957479, -0.00254812219917226,...","[-4.8759066573404116e-05, -0.00015038094235118...","[-0.00010701376880055902, -0.00033651311355943...","[-1.591794990134004e-05, -4.1948602723000726e-..."
19,"Mar 6, 2024 at 7:04:58 AM",Bench,Anwar,34.93,5,225,9,None,16.37,29.12,...,"[0.318, 0.319, 0.32, 0.321, 0.322, 0.322, 0.32...","[-0.073, -0.074, -0.074, -0.074, -0.075, -0.07...","[0.012, 0.012, 0.012, 0.011, 0.012, 0.012, 0.0...","[80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 8...","[-0.002013595661826033, -0.002976289578310601,...","[-0.0019564250831979337, -0.004048498387462733...","[0.000662015196608963, 0.0015926793092593244, ...","[-2.494942620068317e-05, -5.9446523946835814e-...","[-3.0024617353303338e-05, -8.782368276590953e-...","[1.1273472529341436e-05, 3.4522027551588756e-0..."
20,"Jun 4, 2024 at 4:39:47 PM",Bench,Anwar,34.06,5,215,10,None,13.59,26.66,...,"[0.679, 0.677, 0.675, 0.674, 0.674, 0.675, 0.6...","[-2.747, -2.75, -2.752, -2.753, -2.753, -2.752...","[3.001, 3.002, 3.004, 3.006, 3.007, 3.008, 3.0...","[119, 119, 119, 119, 119, 119, 119, 119, 119, ...","[-0.0024775651714639122, -0.00587224433945647,...","[-0.002684807116246779, -0.006296388648758771,...","[0.0018459473581295472, 0.005775188754130713, ...","[-4.174904755460191e-05, -0.000127831184110251...","[-4.490597882502775e-05, -0.000137312424586773...","[3.8105680561301306e-05, 0.0001228209902896172..."
21,"Mar 20, 2024 at 6:46:54 AM",Bench,Anwar,32.89,5,205,7,None,17.86,27.16,...,"[-0.179, -0.179, -0.178, -0.178, -0.178, -0.17...","[0.12, 0.12, 0.121, 0.122, 0.123, 0.123, 0.124...","[0.011, 0.01, 0.008, 0.008, 0.007, 0.006, 0.00...","[95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 9...","[-0.0011430519593629213, -0.002620525001133344...","[0.0004509725030110005, 0.0014844984307660497,...","[-0.0006634361100317153, -0.002667262628258565...","[-1.881788480248133e-05, -5.315788795145626e-0...","[9.677354668885251e-06, 2.0427819587827814e-05...","[-1.6653493691451406e-05, -5.167251749285737e-..."
22,"Mar 29, 2024 at 11:27:04 AM",Bench,Anwar,32.12,3,245,10,None,12.69,22.56,...,"[0.727, 0.728, 0.731, 0.735, 0.74, 0.744, 0.74...","[-2.728, -2.727, -2.726, -2.725, -2.723, -2.72...","[2.982, 2.982, 2.981, 2.979, 2.976, 2.972, 2.9...","[94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 9...","[-0.002223229715770006, -0.004511121134844279,...","[-0.0034114961394830995, -0.01061812093598225,...","[-0.0017588739296770675, -0.005163920289676069...","[-3.367175425307143e-05, -9.559623267482222e-0...","[-7.014808537732676e-05, -0.000229614467533493...","[-3.4613971096765686e-05, -9.993482584284797e-..."
23,"Apr 13, 2024 at 9:23:38 AM",Bench,Anwar,36.61,5,225,9,None,18.35,29.11,...,"[0.211, 0.212, 0.212, 0.212, 0.213, 0.213, 0.2...","[0.081, 0.081, 0.08, 0.079, 0.079, 0.079, 0.07...","[-0.009, -0.008, -0.008, -0.007, -0.006, -0.00...","[91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 9...","[-0.0014449687886944726, -0.001177899771406582...","[-0.002531029962265829, -0.005299150626473317,...","[-0.0005880213807759719, -0.001464862015007399...","[-1.3114342800505277e-05, -1.519775565399505e-...","[-3.915090294369573e-05, -0.000103143972727469...","[-1.0264416978916856e-05, -2.8016482756561632e..."
24,"Apr 27, 2024 at 10:50:24 AM",Bench,Anwar,49.39,4,205,9,None,22.17,34.02,...,"[0.309, 0.307, 0.307, 0.307, 0.307, 0.306, 0.3...","[0.11, 0.11, 0.109, 0.108, 0.107, 0.108, 0.108...","[-0.017, -0.016, -0.015, -0.015, -0.014, -0.01...","[107, 107, 107, 107, 107, 107, 107, 107, 107, ...","[-0.001133779390043993, -0.0002367706091930178...","[-0.001561835684235119, -0.0021501832577431167...","[-0.0014889933577335126, -0.004843404591014526...","[-6.852749996185054e-06, 3.7186889573598375e-0...","[-1.856009470989118e-05, -3.193627954573926e-0...","[-3.166198974374019e-05, -0.000101970801643392..."
25,"Mar 20, 2024 at 6:53:14 AM",Bench,Anwar,37.64,5,225,10,None,15.84,30.52,...,"[0.195, 0.196, 0.196, 0.196, 0.196, 0.195, 0.1...","[0.022, 0.02, 0.02, 0.019, 0.019, 0.02, 0.02, ...","[-0.002, -0.0, 0.002, 0.003, 0.004, 0.005, 0.0...","[87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 8...","[-0.002590732845129262, -0.006380790581328084,...","[-0.0021488426377124607, -0.004460342567622653...","[-0.0009132838785720729, -0.002002981554550003...","[-4.485761713228673e-05, -0.000133913187182556...","[-3.304592602667557e-05, -9.079560174181407e-0...","[-1.458132716561038e-05, -3.504185694764336e-0..."
26,"Jun 4, 2024 at 4:35:41 PM",Bench,Anwar,44.89,5,215,9,None,22,36.06,...,"[0.566, 0.565, 0.564, 0.564, 0.565, 0.564, 0.5...","[-0.041, -0.042, -0.043, -0.044, -0.044, -0.04...","[0.012, 0.013, 0.013, 0.014, 0.015, 0.015, 0.0...","[91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 9...","[-0.004036555859600147, -0.008000254627338218,...","[-0.0038719556313687306, -0.00591700413370678,...","[-1.9488120465676538e-05, -0.00092657647397795...","[-6.018405243469183e-05, -0.000145941454287295...","[-4.894479882537755e-05, -0.000111680975139689...","[-4.730322972218174e-06, -1.9194672441432157e-..."
27,"Mar 20, 2024 at 6:44:41 AM",Bench,Anwar,37.03,8,135,5,None,17.13,30.44,...,"[-0.425, -0.424, -0.424, -0.424, -0.424, -0.42...","[0.348, 0.348, 0.348, 0.348, 0.348, 0.348, 0.3...","[0.076, 0.076, 0.076, 0.077, 0.077, 0.077, 0.0...","[115, 115, 115, 115, 115, 115, 115, 115, 115, ...","[-0.0018616047727279862, -0.003740433431630920...","[0.00040525414892030964, 0.0005231339647142471...","[-0.000638172163273558, -0.0012261799836328668...","[-2.8010191021794534e-05, -7.544516436387748e-...","[4.641940568172784e-06, 1.1125851624088994e-05...","[-9.321760734532123e-06, -2.4072892054133448e-..."
28,"Mar 17, 2024 at 1:37:12 PM",Bench,Anwar,24.60,5,205,7,None,10.73,20.54,...,"[0.62, 0.619, 0.616, 0.61, 0.601, 0.591, 0.583...","[-0.021, -0.022, -0.021, -0.021, -0.019, -0.01...","[0.007, 0.007, 0.008, 0.011, 0.013, 0.018, 0.0...","[107, 107, 107, 107, 107, 107, 107, 107, 107, ...","[-0.006748430179165359, -0.01538153651680548, ...","[-0.009923624852741019, -0.02319305100460582, ...","[0.0032900836113033943, 0.007969999126028204, ...","[-0.00011064983347985419, -0.00032750591840246...","[-0.0001655833792867342, -0.000484592685389623...","[5.630041368665799e-05, 0.00017210012258232098..."
29,"Apr 27, 2024 at 10:45:57 AM",Bench,Anwar,40.81,5,205,8,None,22.06,34.11,...,"[-0.127, -0.127, -0.127, -0.127, -0.129, -0.13...","[0.255, 0.254, 0.254, 0.253, 0.253, 0.253, 0.2...","[0.016, 0.015, 0.015, 0.015, 0.016, 0.016, 0.0...","[105, 105, 105, 105, 105, 105, 105, 105, 105, ...","[-0.004497556128023782, -0.008453690267395028,...","[2.8543025352660012e-05, 0.0004881882316647384...","[-0.0013530618120945756, -0.003375210419986851...","[-6.475623197709406e-05, -0.000162717440302413...","[2.5836562850869925e-06, 1.6244408956652565e-0...","[-2.3641361160407132e-05, -6.792501267235973e-..."
30,"Jun 4, 2024 at 4:44:20 PM",Bench,Anwar,47.34,8,185,9,None,17.94,38.00,...,"[0.301, 0.301, 0.301, 0.302, 0.302, 0.302, 0.3...","[0.004, 0.004, 0.004, 0.003, 0.002, 0.002, 0.0...","[-0.001, 0.0, 0.001, 0.002, 0.003, 0.004, 0.00...","[96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 9...","[-0.0008106859681024626, 0.0002617303918598873...","[-0.0011090226819511415, -0.002103039052818112...","[-0.0009034969609946139, -0.001870365064206028...","[-2.744777881212876e-06, 1.4750332154485163e-0...","[-1.6060308673846268e-05, -4.423597285699452e-...","[-1.3869310126003214e-05, -3.6074331565342606e..."
31,"Apr 20, 2024 at 10:40:27 AM",Bench,Anwar,46.73,5,215,9,None,23.48,37.6,...,"[-0.408, -0.407, -0.407, -0.407, -0.408, -0.40...","[0.226, 0.225, 0.224, 0.223, 0.222, 0.221, 0.2...","[0.047, 0.045, 0.043, 0.041, 0.039, 0.036, 0.0...","[105, 105, 105, 105, 105, 105, 105, 105, 105, ...","[-0.002401904435261115, -0.005076571247206049,...","[-0.00043432346452752655, -0.00054568030636721...","[-0.00014443275167809168, 9.256817264420114e-0...","[-3.7392378412335826e-05, -0.00010287076454754...","[-4.900018854473684e-06, -1.0573807579178704e-...","[-2.593228951694527e-07, -3.491492940046146e-0..."
32,"Apr 27, 2024 at 10:54:44 AM",Bench,Anwar,40.65,9,155,8,Lost count of reps could be 8 or 10 too,16.01,34.46,...,"[-0.111, -0.112, -0.113, -0.114, -0.114, -0.11...","[0.285, 0.285, 0.285, 0.285, 0.285, 0.285, 0.2...","[0.016, 0.016, 0.017, 0.018, 0.019, 0.02, 0.02...","[107, 107, 107, 107, 107, 107, 107, 107, 107, ...","[-0.0027047026495927054, -0.006520062972675388...","[-0.0004601039542305006, -0.002689655797920670...","[-0.0006505661126691933, -0.000743434247383995...","[-4.612382811134047e-05, -0.000136130302682496...","[-1.5748798760755854e-05, -6.031577256163724e-...","[-6.970001800265943e-06, -1.4505237323828887e-..."

## Define feature extraction

In [82]:
from scipy.stats import skew, kurtosis

In [83]:
def safe_float_convert(value):
    try:
        return float(value)
    except ValueError:
        return np.nan

def parse_column(column_data):
    return np.array([safe_float_convert(x) for x in column_data.split(',')])

def extract_fft_features(window):
    fft = np.fft.fft(window)
    magnitudes = np.abs(fft)
    freqs = np.fft.fftfreq(len(fft), d=1/SAMPLE_RATE)
    magnitudes = magnitudes[freqs >= 0]
    top_5_freq_indices = np.argsort(magnitudes)[::-1][:5]
    top_5_magnitudes = magnitudes[top_5_freq_indices]

    return top_5_magnitudes.tolist()

def extract_features(window):
    mean = np.mean(window)
    std = np.std(window)
    abs_dev = np.mean(np.abs(window - np.mean(window)))
    median = np.median(window)
    median_abs_dev = np.median(np.abs(window - median))
    iqr = np.percentile(window, 75) - np.percentile(window, 25)
    neg_count = np.sum(window < 0)
    pos_count = np.sum(window > 0)
    above_mean_count = np.sum(window > mean)
    num_peaks = len(find_peaks(window)[0])
    energy = np.sum(window ** 2)
    skewness = skew(window)
    kurt = kurtosis(window)
    avg_resultant_acc = np.mean(np.sqrt(window ** 2))
    sma = np.sum(np.abs(window))
    
    features = [mean,
                std,
                abs_dev,
                median,
                median_abs_dev,
                iqr,
                neg_count,
                pos_count,
                above_mean_count,
                num_peaks,
                energy,
                skewness,
                kurt,
                avg_resultant_acc,
                sma]
    
    features += extract_fft_features(window)    
    return features

## Train a exercise classifier

In [84]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [86]:
df['AccXFeatures'] = df['AccX'].apply(lambda x: extract_features(x))
df['AccYFeatures'] = df['AccY'].apply(lambda x: extract_features(x))
df['AccZFeatures'] = df['AccZ'].apply(lambda x: extract_features(x))
df['VelXFeatures'] = df['VelX'].apply(lambda x: extract_features(x))
df['VelYFeatures'] = df['VelY'].apply(lambda x: extract_features(x))
df['VelZFeatures'] = df['VelZ'].apply(lambda x: extract_features(x))
df['PosXFeatures'] = df['PosX'].apply(lambda x: extract_features(x))
df['PosYFeatures'] = df['PosY'].apply(lambda x: extract_features(x))
df['PosZFeatures'] = df['PosZ'].apply(lambda x: extract_features(x))
df['PitchFeatures'] = df['Pitch'].apply(lambda x: extract_features(x))
df['RollFeatures'] = df['Roll'].apply(lambda x: extract_features(x))
df['YawFeatures'] = df['Yaw'].apply(lambda x: extract_features(x))

for col in ['AccXFeatures', 'AccYFeatures', 'AccZFeatures', 'VelXFeatures', 'VelYFeatures', 'VelZFeatures', 'PosXFeatures', 'PosYFeatures', 'PosZFeatures', 'PitchFeatures', 'RollFeatures', 'YawFeatures']:
    if isinstance(df[col].iloc[0], list):
        df[col] = df[col].apply(lambda x: x[0] if isinstance(x, list) else x)

accx_features = np.array(df['AccXFeatures'].tolist())
accy_features = np.array(df['AccYFeatures'].tolist())
accz_features = np.array(df['AccZFeatures'].tolist())
velx_features = np.array(df['VelXFeatures'].tolist())
vely_features = np.array(df['VelYFeatures'].tolist())
velz_features = np.array(df['VelZFeatures'].tolist())
posx_features = np.array(df['PosXFeatures'].tolist())
posy_features = np.array(df['PosYFeatures'].tolist())
posz_features = np.array(df['PosZFeatures'].tolist())
pitch_features = np.array(df['PitchFeatures'].tolist())
roll_features = np.array(df['RollFeatures'].tolist())
yaw_features = np.array(df['YawFeatures'].tolist())

df

Training accuracy:  1.0
Testing accuracy:  1.0
              precision    recall  f1-score   support

       Bench       1.00      1.00      1.00         9

    accuracy                           1.00         9
   macro avg       1.00      1.00      1.00         9
weighted avg       1.00      1.00      1.00         9

In [ ]:
X = df[['AccXFeatures', 'AccYFeatures', 'AccZFeatures', 'VelXFeatures', 'VelYFeatures', 'VelZFeatures', 'PosXFeatures', 'PosYFeatures', 'PosZFeatures', 'PitchFeatures', 'RollFeatures', 'YawFeatures']]
y = df['Exercise']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_STATE)

clf = RandomForestClassifier(n_estimators=N_ESTIMATORS, max_depth=MAX_DEPTH, random_state=RANDOM_STATE)
clf.fit(X_train, y_train)

print("Training accuracy: ", clf.score(X_train, y_train))
print("Testing accuracy: ", clf.score(X_test, y_test))

y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred, zero_division=0))

## Train a predictor for whether is in rep state or non rep state

 For entries with a RepStartTime and RepEndTime
 - Extract windows for each axes
 - Label window with 0 or 1 depending on whether it is between RepStartTime and RepEndTime
 - Create a classifier for this data

### Extract windows

In [88]:
## Train a predictor for whether is in rep state or non rep state

# For entries with a RepStartTime and RepEndTime
# - Extract windows for each axes
# - Label window with 0 or 1 depending on whether it is between RepStartTime and RepEndTime
# - Create a classifier for this data

def extract_windows(data, window_size, overlap):
    windows = []
    for i in range(0, len(data) - window_size, window_size - overlap):
        windows.append(data[i:i+window_size])
    return np.array(windows)

def extract_window_features(window):
    features = []
    for i in range(len(window)):
        features.append(extract_features(window[i]))
    return features

In [89]:
df['AccXWindows'] = df.apply(lambda x: extract_windows(x['AccX'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['AccYWindows'] = df.apply(lambda x: extract_windows(x['AccY'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['AccZWindows'] = df.apply(lambda x: extract_windows(x['AccZ'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['VelXWindows'] = df.apply(lambda x: extract_windows(x['VelX'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['VelYWindows'] = df.apply(lambda x: extract_windows(x['VelY'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['VelZWindows'] = df.apply(lambda x: extract_windows(x['VelZ'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['PosXWindows'] = df.apply(lambda x: extract_windows(x['PosX'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['PosYWindows'] = df.apply(lambda x: extract_windows(x['PosY'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['PosZWindows'] = df.apply(lambda x: extract_windows(x['PosZ'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['PitchWindows'] = df.apply(lambda x: extract_windows(x['Pitch'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['RollWindows'] = df.apply(lambda x: extract_windows(x['Roll'], WINDOW_SIZE, STEP_SIZE), axis=1)
df['YawWindows'] = df.apply(lambda x: extract_windows(x['Yaw'], WINDOW_SIZE, STEP_SIZE), axis=1)

df['AccXWindowFeatures'] = df['AccXWindows'].apply(lambda x: extract_window_features(x))
df['AccYWindowFeatures'] = df['AccYWindows'].apply(lambda x: extract_window_features(x))
df['AccZWindowFeatures'] = df['AccZWindows'].apply(lambda x: extract_window_features(x))
df['VelXWindowFeatures'] = df['VelXWindows'].apply(lambda x: extract_window_features(x))
df['VelYWindowFeatures'] = df['VelYWindows'].apply(lambda x: extract_window_features(x))
df['VelZWindowFeatures'] = df['VelZWindows'].apply(lambda x: extract_window_features(x))
df['PosXWindowFeatures'] = df['PosXWindows'].apply(lambda x: extract_window_features(x))
df['PosYWindowFeatures'] = df['PosYWindows'].apply(lambda x: extract_window_features(x))
df['PosZWindowFeatures'] = df['PosZWindows'].apply(lambda x: extract_window_features(x))
df['PitchWindowFeatures'] = df['PitchWindows'].apply(lambda x: extract_window_features(x))
df['RollWindowFeatures'] = df['RollWindows'].apply(lambda x: extract_window_features(x))
df['YawWindowFeatures'] = df['YawWindows'].apply(lambda x: extract_window_features(x))

df

,Date,Exercise,Lifter,WorkoutTime,Reps,Weight,Intensity,Notes,StartRepTime,EndRepTime,...,AccZWindowFeatures,VelXWindowFeatures,VelYWindowFeatures,VelZWindowFeatures,PosXWindowFeatures,PosYWindowFeatures,PosZWindowFeatures,PitchWindowFeatures,RollWindowFeatures,YawWindowFeatures
0,"Apr 27, 2024 at 10:41:29 AM",Bench,Anwar,35.35,6,205,9,None,13.44,27.93,...,"[[0.12641470531101925, 0.7816404723942529, 0.5...","[[0.10881467661861953, 0.21914133954178608, 0....","[[-0.1319753779856032, 0.1618459840410315, 0.1...","[[0.10104759309035469, 0.12292886458033951, 0....","[[0.02288252207225806, 0.05204364286550529, 0....","[[-0.06828153058665257, 0.058028969497788005, ...","[[0.021273453699936936, 0.036774292819226305, ...","[[-0.19649999999999998, 0.5931789864787862, 0....","[[-0.11749000000000001, 0.16218936432454503, 0...","[[0.30466, 0.30962584582040303, 0.285912799999..."
1,"Mar 6, 2024 at 7:00:55 AM",Bench,Anwar,35.75,4,240,10,None,15.04,28.92,...,"[[0.33832866013288465, 1.6101891275554787, 1.4...","[[0.022588556600392537, 0.13884784526959346, 0...","[[-0.4818591161570933, 0.3999216288507775, 0.3...","[[-0.1524066071568525, 0.24769373614822487, 0....","[[-0.02312460008962877, 0.020419631855180313, ...","[[-0.1329517584957437, 0.14543250170618674, 0....","[[-0.09654330183876755, 0.07576007360742512, 0...","[[-0.58213, 0.24629533714628055, 0.2073604, -0...","[[0.3370100000000001, 0.3918107832870351, 0.29...","[[0.72996, 0.7653667999070772, 0.6146271999999..."
2,"Mar 6, 2024 at 6:53:59 AM",Bench,Anwar,29.18,5,225,8,None,13.53,24.54,...,"[[1.0422830453762297, 1.1387353921342265, 0.96...","[[0.3963764314758479, 0.5103894738005159, 0.47...","[[-0.4736032830122279, 0.2633623822039388, 0.2...","[[0.46852661298490433, 0.34354973357916324, 0....","[[0.06433974128197148, 0.13420516992338766, 0....","[[-0.1964987113716328, 0.16591325917447733, 0....","[[0.1413509465450143, 0.14280745596550246, 0.1...","[[-0.27898, 0.5263652340343158, 0.477720799999...","[[0.38741, 0.5854182111106555, 0.5266694000000...","[[1.2048800000000002, 1.2243440552393758, 1.10..."
3,"Mar 6, 2024 at 6:50:48 AM",Bench,Anwar,27.94,5,185,5,None,13.95,23.43,...,"[[-0.211329714193789, 0.5938076022221245, 0.40...","[[0.15124958804405586, 0.19137480928790765, 0....","[[-0.21815382902917513, 0.15664553927202415, 0...","[[-0.1568514108305436, 0.1038830218183456, 0.0...","[[0.028338972433379656, 0.04618151903276008, 0...","[[-0.06661938653783225, 0.06707523938262253, 0...","[[-0.05311221769230683, 0.05124890671243611, 0...","[[-0.35761000000000004, 0.1091510783272433, 0....","[[0.1899, 0.13116306644783812, 0.1163059999999...","[[0.23318999999999998, 0.20867844617976242, 0...."
4,"Mar 2, 2024 at 2:50:08 PM",Bench,Anwar,26.90,5,205,7,None,13.00,22.62,...,"[[-0.07014234789777964, 0.5913702881959929, 0....","[[-0.030257920226447122, 0.07240997123644521, ...","[[-0.04898282656993937, 0.037752355277824654, ...","[[0.02911485676719622, 0.06503129120294049, 0....","[[-0.008166115094484575, 0.00681426461818763, ...","[[-0.021207926475698198, 0.01788418107293271, ...","[[0.009335511792077495, 0.015041759683225523, ...","[[0.56269, 0.05487434646535665, 0.048593399999...","[[-0.08189, 0.07628314296094517, 0.07043680000...","[[0.15032, 0.1516058626834728, 0.1381711999999..."
5,"Jun 4, 2024 at 4:32:13 PM",Bench,Anwar,36.65,6,205,8,None,16.88,30.08,...,"[[0.03603655521190381, 1.3227295657307248, 0.8...","[[0.11205005958443044, 0.302772963652854, 0.26...","[[0.05255918994698911, 0.22877404611128532, 0....","[[0.13582490231963987, 0.13136219934559132, 0....","[[0.056900935160182825, 0.06821548536288331, 0...","[[-0.014282276875090634, 0.02558032756057549, ...","[[0.042702055176147564, 0.04943315581221595, 0...","[[-0.33201, 0.4930592559723425, 0.471450200000...","[[-0.03086, 0.07190382743637504, 0.05548919999...","[[0.32230000000000003, 0.30525269859577, 0.282..."
6,"Mar 17, 2024 at 1:43:08 PM",Bench,Anwar,36.49,5,225,9,None,17.11,30.2,...,"[[0.5595327969541914, 0.5793826828020393, 0.50...","[[0.2041238394478434, 0.27478739886758125, 0.2...","[[-0.2154973421584314, 0.14986656316358357, 0....","[[0.21554314508296563, 0.17112792531473542, 0....","[[0.03958748430098352, 0.07592055074367994, 0....","[[-0.09637277936036602, 0.07986540745614185, 0...","[[0.061892587543081176, 0.0659608557426286, 0....","[[-0.22294, 0.5233598536380107, 0.4796528, -0....","[[-0.057580000000000006, 0.11719719962524701, ...","[[0.32022999999999996, 0.34094873089659683, 0...."
7,"Apr 20, 2024 at 10:36:11 AM",Bench,Anwar,50.23,6,215,9,None,23.24,39.18,...,"[[0.31591604834059767, 0.8096585962340904, 0.6...","[[0.11400654623267416, 0.2359173881432601, 0.2...","[[-0.11324184805661139, 0.13942101752263875, 0...","[[0.2183014362775227, 0.17251215326318586, 0.1...","[[0.03899438841480364, 0.05818993190970078, 0....","[[-0.06170565058066759, 0.04982774923901798, 0...","[[0.06700267003386237, 0.07368615753059773, 0....","[[-0.27676, 0.6087212518057835, 0.5679456, -0....","[[0.01618, 0.08408202899549938, 0.0742204, 0.0...","[[0.34704999999999997, 0.36046582015497675, 0...."
8,"Apr 27, 2024 at 10:37:28 AM",Bench,Anwar,27.82,7,135,5,None,12.19,22.79,...,"[[-0.057783683503860886, 1.1887408753705884, 0...","[[-0.032848105155852556, 0.029835352355462832,...","[[0.09053013295623784, 0.1276239418051825, 0.0...","[[-0.08267266514140738, 0.04972620881286655, 0...","[[-0.010289172425342209, 0.01081600012929648, ...","[[0.023558359121877013, 0.02091922139651244, 0...","[[-0.034846586988596134, 0.027027596848519696,...","[[-0.05752000000000001, 0.043829779830612876, ...","[[0.21626, 0.041019902486476, 0.0332344, 0.197...","[[0.08840999999999999, 0.10470301762604553, 0...."
9,"Mar 20, 2024 at 6:49:19 AM",Bench,Anwar,37.38,5,225,9,None,18.36,30.29,...,"[[-0.31981264255536035, 0.5314375713127572, 0....","[[0.10163929331659655, 0.1358033268527891, 0.1...","[[-0.10253919506849513, 0.07751970855836787, 0...","[[-0.08942493296400303, 0.12991730243771896, 0...","[[0.016845249114982083, 0.03602609325744156, 0...","[[-0.04642708536482684, 0.0379827942326433, 0....","[[-0.011570243419024922, 0.02824742404560647, ...","[[0.3586, 0.2760001449274982, 0.24496, 0.5105,...","[[-0.30582999999999994, 0.33313724063814903, 0...","[[0.20065000000000002, 0.16575176469648822, 0...."
10,"Apr 23, 2024 at 6:49:03 AM",Bench,Anwar,44.42,8,185,9,None,16.59,37.31,...,"[[0.33392144772229676, 1.0411511177918145, 0.8...","[[-0.004497078091287532, 0.04558217790202452, ...","[[-0.20874573651890993, 0.14327245243216055, 0...","[[0.1135604743994052, 0.16609088262986385, 0.1...","[[-0.009845236545317116, 0.006337548899255076,...","[[-0.08569993408928726, 0.07537791445554705, 0...","[[0.020473946984999828, 0.03219490644064857, 0...","[[-0.3636600000000001, 0.12747848602803535, 0....","[[0.29864, 0.12417580440649457, 0.102206400000...","[[0.36312000000000005, 0.31181444097411526, 0...."
11,"Mar 20, 2024 at 6:57:06 AM",Bench,Anwar,47.05,4,225,10,None,30.11,40.6,...,"[[-0.1399754081493035, 1.412463685347843, 0.77...","[[-0.06145301964498254, 0.07995546197806469, 0...","[[-0.10259527368180885, 0.10803399706487102, 0...","[[-0.04676638185090244, 0.060783689612752316, ...","[[-0.011516409621883343, 0.017474328036442346,...","[[-0.027299237546336765, 0.03130832818197485, ...","[[-0.024758962368531746, 0.017789233944008827,...","[[-0.7053899999999997, 0.4465746498627077, 0.4...","[[0.48639999999999994, 0.27843300810069194, 0....","[[0.32034, 0.3120323771662165, 0.2797880000000..."
12,"Apr 20, 2024 at 10:32:54 AM",Bench,Anwar,39.02,6,215,9,None,17.56,31.14,...,"[[-0.6656888275868116, 0.8564893952555367, 0.7...","[[-0.014095852711467289, 0.18690249220219596, ...","[[-0.10439114134912705, 0.11256609850466008, 0...","[[-0.1443535046604638, 0.23020239964550193, 0....","[[-0.03871964792982456, 0.029347203853969613, ...","[[-0.04189733802158552, 0.04121513519697828, 0...","[[-0.01648989850863897, 0.04062438261990015, 0...","[[-0.37656, 0.14857687033990183, 0.11943520000...","[[0.044909999999999985, 0.3071767925804292, 0....","[[0.04503, 0.10146649249875547, 0.0653602, 0.0..."
13,"Mar 17, 2024 at 1:39:49 PM",Bench,Anwar,37.01,5,225,8,None,18.62,31.3,...,"[[-0.1097014363180077, 0.6195567251163688, 0.4...","[[0.027920646115143537, 0.05638520047602589, 0...","[[-0.30603129880945, 0.13130404117114655, 0.11...","[[0.054538072653590744, 0.0747175097628797, 0....","[[0.0035681053783997206, 0.012221091974378403,...","[[-0.12140743800168144, 0.09738096767620928, 0...","[[0.03001436191043854, 0.024895975714796775, 0...","[[0.6806700000000001, 0.18228999177135316, 0.1...","[[-0.15323000000000003, 0.09424413562657359, 0...","[[0.20550000000000002, 0.1947497625159014, 0.1..."
14,"Apr 20, 2024 at 10:45:07 AM",Bench,Anwar,40.71,9,175,9,None,13.67,34.39,...,"[[0.22018420650405818, 1.5843013140970335, 1.2...","[[0.19043816179924292, 0.23630979764111734, 0....","[[-0.2624239842358522, 0.23042750324344077, 0....","[[-0.0663263057352304, 0.17661736706889267, 0....","[[0.057367821313510585, 0.0775531755113681, 0....","[[-0.07550282017020586, 0.08311633072172017, 0...","[[-0.033155189689154665, 0.04098240930302603, ...","[[0.8627100000000002, 0.32234041927750856, 0.2...","[[-2.1833400000000003, 0.17538222372863224, 0....","[[2.31851, 0.18876066830778068, 0.155321, 2.30..."
15,"Mar 29, 2024 at 11:30:42 AM",Bench,Anwar,38.93,3,245,10,None,18.62,27.2,...,"[[0.3328229730385882, 0.8983179444869243, 0.67...","[[0.1372785424533344, 0.23113379863293, 0.2038...","[[-0.0636550694447418, 0.16243239492580702, 0....","[[0.2126959712938164, 0.17117509398230052, 0.1...","[[0.029192947243486173, 0.06002489744339754, 0...","[[-0.05204348690915757, 0.038619710570785344, ...","[[0.0668305683545522, 0.07370895653762001, 0.0...","[[-0.20453, 0.5296906730347439, 0.497241799999...","[[-0.02783, 0.049986409152888746, 0.04133, -0....","[[0.40903, 0.42028793594391933, 0.387713599999..."
16,"Mar 2, 2024 at 3:02:48 PM",Bench,Anwar,38.83,5,235,10,None,14.82,31.70,...,"[[0.031224959462385852, 1.1457238255722504, 0....","[[-0.3270335005912676, 0.14046813612080236, 0....","[[-0.43302417397195453, 0.2074666200881981, 0....","[[0.08655044782495476, 0.07539686735784489, 0....","[[-0.13472246818392156, 0.10631599287125074, 0...","[[-0.1751255749686821, 0.14361056770835265, 0....","[[0.043838593710050604, 0.0322935659979672, 0....","[[-0.29275, 0.3098113095095142, 0.292225, -0.2...","[[0.25310000000000005, 0.14778068209343198, 0....","[[0.34639, 0.35135585650448464, 0.306860199999..."
17,"Mar 2, 2024 at 2:58:28 PM",Bench,Anwar,36.47,5,235,9,None,16.30,29.79,...,"[[-0.05263969702028322, 0.9546108988017554, 0....","[[-0.14054968503006474, 0.13243649191819623, 0...","[[-0.08763450545907499, 0.09348192239460743, 0...","[[-0.010680736468968978, 0.02788335583488159, ...","[[-0.03829550045679941, 0.03757658277439394, 0...","[[-0.02280260913877967, 0.029481648967530506, ...","[[-0.00715800365368932, 0.004010326419124812, ...","[[-0.49282, 0.06613597810571792, 0.060342, -0....","[[0.29947, 0.0455469988034338, 0.0349709999999...","[[0.18169000000000005, 0.13763783600449406, 0...."
18,"Mar 17, 2024 at 1:46:35 PM",Bench,Anwar,42.65,5,225,10,None,21.86,35.71,...,"[[0.5973116584506946, 0.8575418770558827, 0.61...","[[-0.13169581229619418, 0.18029105019099392, 0...","[[-0.8261715809518384, 0.3654762626567602, 0.3...","[[0.33394506642706223, 0.21365255925609972, 0....","[[-0.042990282517246084, 0.02883824853018366, ...","[[-0.3219902181330194, 0.25871044385883546, 0....","[[0.11245487970695893, 0.10687268202307325, 0....","[[-0.23717000000000002, 0.6100592275345076, 0....","[[-0.33541, 0.29180911894593015, 0.27158899999...","[[0.25786, 0.18520556255145254, 0.168708, 0.34..."
19,"Mar 6, 2024 at 7:04:58 AM",Bench,Anwar,34.93,5,225,9,None,16.37,29.12,...,"[[0.006518505281666809, 0.9559969059432908, 0....","[[0.0027182963451420706, 0.08647268379861954, ...","[[-0.06515016056037755, 0.12126806534787761, 0...","[[0.0022097404858598207, 0.10196132854244674, ...","[[0.0073955899073469104, 0.011294112336883974,...","[[-0.04937438180141801, 0.03176472846528842, 0...","[[0.015388661573380842, 0.014340709311135262, ...","[[0.17570999999999998, 0.11542333342959733, 0....","[[-0.14634, 0.06144724892133089, 0.05038719999...","[[0.13624, 0.08682051831220544, 0.0813272, 0.1..."
20,"Jun 4, 2024 at 4:39:47 PM",Bench,Anwar,34.06,5,215,10,None,13.59,26.66,...,"[[0.32955953439274116, 1.200764973498471, 0.70...","[[0.1394114451929701, 0.2057442864099563, 0.19...","[[-0.30067611051072785, 0.2470677710845303, 0....","[[0.27432845995499905, 0.17175552316822248, 0....","[[0.023759854793838707, 0.053667158796862464, ...","[[-0.11267126608971965, 0.10914291436109712, 0...","[[0.09373745681018628, 0.08532933106570643, 0....","[[0.46673000000000003, 0.27171020794221185, 0....","[[-2.57909, 0.1944922669413877, 0.171532000000...","[[2.67091, 0.37190423753971935, 0.341246199999..."
21,"Mar 20, 2024 at 6:46:54 AM",Bench,Anwar,32.89,5,205,7,None,17.86,27.16,...,"[[0.20584757610208107, 0.34613015374063877, 0....","[[0.013426382232536177, 0.030782234574331168, ...","[[-0.12696084491370707, 0.08707083239359087, 0...","[[0.10842552409506727, 0.06685949910172632, 0....","[[0.004471281972840511, 0.007318718561474338, ...","[[-0.05260822055356992, 0.04621131334821881, 0...","[[0.03662189381716506, 0.03364424932443392, 0....","[[-0.32841000000000004, 0.14777145157302882, 0...","[[0.17181000000000002, 0.035717697294198575, 0...","[[0.35039000000000003, 0.28823340871592246, 0...."
22,"Mar 29, 2024 at 11:27:04 AM",Bench,Anwar,32.12,3,245,10,None,12.69,22.56,...,"[[-0.19542278495319562, 1.4640182041064413, 0....","[[0.15993511114516934, 0.22999851893350898, 0....","[[-0.44462146757542875, 0.28217463155527084, 0...","[[-0.03268893750200015, 0.07567220176510984, 0...","[[0.03256645476029888, 0.06295402689458277, 0....","[[-0.1674134175600803, 0.15219132849401013, 0....","[[-0.010022243169097873, 0.0067482800457967, 0...","[[0.53656, 0.2533387581875304, 0.2309968, 0.71...","[[-2.5193599999999994, 0.21182802080933488, 0....","[[2.6647599999999994, 0.33148185832711874, 0.3..."
23,"Apr 13, 2024 at 9:23:38 AM",Bench,Anwar,36.61,5,225,9,None,18.35,29.11,...,"[[0.09167348014627859, 0.5105803464695999, 0.3...","[[0.12040874606479036, 0.2328013498985542, 0.1...","[[-0.08357001407517817, 0.0404513660913399, 0....","[[0.1192676614437524, 0.07810524732142134, 0.0...","[[0.07128032203199094, 0.06425075527607986, 0....","[[-0.03599338746965277, 0.02702092105077167, 0...","[[0.04669502107681388, 0.04276221476275217, 0....","[[-0.24121999999999996, 0.41673362187373364, 0...","[[0.005879999999999999, 0.05833100033429908, 0...","[[0.35062000000000004, 0.3160591330748093, 0.2..."
24,"Apr 27, 2024 at 10:50:24 AM",Bench,Anwar,49.39,4,205,9,None,22.17,34.02,...,"[[-0.16026462976133643, 0.8624866289084219, 0....","[[0.19861983382740508, 0.1731732658904207, 0.1...","[[0.09697065588451886, 0.14781410511964369, 0....","[[0.030785590090151395, 0.11456902873351045, 0...","[[0.08503848110301687, 0.07791199230092818, 0....","[[0.01346206941307208, 0.02794436677622838, 0....","[[0.020665996659859746, 0.02401357266857776, 0...","[[-0.21811999999999998, 0.4173766711257351, 0....","[[0.10283000000000002, 0.034680846298785734, 0...","[[0.38970999999999995, 0.35118537255984905, 0...."
25,"Mar 20, 2024 at 6:53:14 AM",Bench,Anwar,37.64,5,225,10,None,15.84,30.52,...,"[[0.1429041064738289, 0.40785297619303634, 0.2...","[[0.07985048404465825, 0.17534155559369022, 0....","[[-0.05614461654312716, 0.06710368720041235, 0...","[[0.05217204322795008, 0.04760053319746173, 0....","[[0.0015663672881036223, 0.03549547185605761, ...","[[-0.033815909467162356, 0.024238354362698472,...","[[0.014483435564376888, 0.017029041417830973, ...","[[-0.09808000000000001, 0.32862074432390903, 0...","[[-0.13919, 0.17718643825078714, 0.1595604, -0...","[[0.22609, 0.2500100835966421, 0.2289061999999..."
26,"Jun 4, 2024 at 4:35:41 PM",Bench,Anwar,44.89,5,215,9,None,22,36.06,...,"[[0.131520891309838, 1.2967549862834242, 1.020...","[[0.18451228763043181, 0.3283680202872358, 0.2...","[[0.08932627121260765, 0.23015363687191487, 0....","[[0.23104855604774635, 0.2045463153893337, 0.1...","[[0.07364571666929642, 0.08995775975843852, 0....","[[-0.005799346889313999, 0.02987514326034859, ...","[[0.07436493610569742, 0.08283025117931223, 0....","[[-0.06338, 0.6379058359977592, 0.591593199999...","[[-0.11559000000000001, 0.11502983047888056, 0...","[[0.342, 0.34209495757757086, 0.3033, 0.231499..."
27,"Mar 20, 2024 at 6:44:41 AM",Bench,Anwar,37.03,8,135,5,None,17.13,30.44,...,"[[-0.09132361962544118, 0.44535073242013595, 0...","[[-0.04209110240314931, 0.02712340663934887, 0...","[[0.007832290282971869, 0.023925519995261522, ...","[[0.014853767339907238, 0.036256064090386106, ...","[[-0.024769801781568818, 0.014987593700770595,...","[[0.003228399498668665, 0.0022431828616975248,...","[[0.005889518263275064, 0.008043014641584672, ...","[[-0.42245, 0.007115300415302231, 0.0055220000...","[[0.4579399999999999, 0.10896786865860963, 0.0...","[[0.21173999999999998, 0.1455343684495178, 0.1..."
28,"Mar 17, 2024 at 1:37:12 PM",Bench,Anwar,24.60,5,205,7,None,10.73,20.54,...,"[[0.4927611485874206, 0.9182848787823307, 0.80...","[[-0.5032393603902466, 0.3372268621615825, 0.2...","[[-0.7285294587715505, 0.3627573607093007, 0.2...","[[0.2735075445334194, 0.11828385257031651, 0.0...","[[-0.16088326161678032, 0.14747857006343035, 0...","[[-0.26914375761044396, 0.21740320313426476, 0...","[[0.12066400588516521, 0.08295031125752245, 0....","[[0.50037, 0.07685124006806916, 0.0681604, 0.5...","[[0.040119999999999996, 0.035508950984223686, ...","[[0.22772000000000003, 0.11339595054498199, 0...."
29,"Apr 27, 2024 at 10:45:57 AM",Bench,Anwar,40.81,5,205,8,None,22.06,34.11,...,"[[0.3334077861818805, 0.951045122079976, 0.772...","[[-0.004262641745464817, 0.05401276726453558, ...","[[0.05908961331483587, 0.2292503061956973, 0.1...","[[-0.004166217274268851, 0.1439477911256039, 0...","[[-0.01409891847106134, 0.008538807907255972, ...","[[0.0013702473866151626, 0.02077110772144368, ...","[[-0.02390211550999815, 0.02067564742895992, 0...","[[-0.28056, 0.1348827134958368, 0.124353600000...","[[0.26656, 0.0173668189372723, 0.0152656, 0.25...","[[0.20929000000000003, 0.20780612575186516, 0...."
30,"Jun 4, 2024 at 4:44:20 PM",Bench,Anwar,47.34,8,185,9,None,17.94,38.00,...,"[[0.18753672244041522, 0.7124539438590174, 0.5...","[[0.32275735998435856, 0.26647858599419466, 0....","[[-0.006916617485002553, 0.15118880540966725, ...","[[0.16563973577494284, 0.14532850054467264, 0....","[[0.12156460501506469, 0.1203261560206769, 0.1...","[[-0.027483391031234997, 0.023061265004448755,...","[[0.049737815432166446, 0.058520692354415337, ...","[[-0.358, 0.6216887806611923, 0.58416, -0.2090...","[[-0.00014000000000000012, 0.12172296578706912...","[[0.36674000000000007, 0.35472061174958525, 0...."
31,"Apr 20, 2024 at 10:40:27 AM",Bench,Anwar,46.73,5,215,9,None,23.48,37.6,...,"[[-0.1908196594955097, 0.8092669228254995, 0.5...","[[-0.039915299812947315, 0.03650889121068304, ...","[[0.0315494356370149, 0.06696636919987058, 0.0...","[[-0.007021546308968068, 0.07211965675643493, ...","[[-0.014493428798554647, 0.009521621277463256,...","[[0.01071669765099873, 0.01608591951059957, 0....","[[0.0021626579805258395, 0.007571553548710198,...","[[-0.33031999999999995, 0.050972321901204376, ...","[[0.24434, 0.03643191458048835, 0.0329944, 0.2...","[[0.11359, 0.07017109020102223, 0.065950999999..."

### Extract labels

In [115]:
def calculate_sample_index(time, sample_rate):
    return int(float(time)* float(sample_rate))

def label_data(data, start_time, end_time, sample_rate):    
    start_index = calculate_sample_index(start_time, sample_rate)
    end_index = calculate_sample_index(end_time, sample_rate)
    
    labels = np.zeros(len(data))
    labels[start_index:end_index] = 1
    
    return labels

def label_windows(data, labels, window_size):
    window_labels = []
    for i in range(0, len(data) - window_size, window_size):
        window_labels.append(1 if np.sum(labels[i:i+window_size]) > window_size/2 else 0)
    return np.array(window_labels)

In [123]:
df['Labels'] = df.apply(lambda x: label_data(x['Counter'], x['StartRepTime'], x['EndRepTime'], SAMPLE_RATE), axis=1)
df['WindowLabels'] = df.apply(lambda x: label_windows(x['Counter'], x['Labels'], WINDOW_SIZE), axis=1)